/**
 * 다락방 소품 (houseProps.ts, 사람 크기) 의 손찍기 격자. 한 칸씩 직접 찍었다 (견본 화풍: 둥근 실루엣 · 3단 명암 · 왼쪽 위 빛 · 반짝 조금).
 * 글자는 소품마다 팔레트 한 줄(houseProps.ts 의 PAL)로 칠한다. 이 파일 안 글자의 뜻:
 *   . u W w v 나무 (밝음 · 바탕 · 그늘 · 깊은 그늘)   G g C c j 주된 색 (반짝 · 밝음 · 바탕 · 그늘 · 깊은 그늘)
 *   . h A a s 둘째 색   . l B b n 셋째 색   O o P p y 종이 · 천   I i M m z 쇠 · 유리 · 밤하늘   Q q K k x 골판지
 *   X 먹 (눈 · 글씨 · 깊은 틈) · 1~9 포인트 색 (팔레트마다 다름)
 * 외곽선은 그릴 때 따뜻한 먹색으로 두른다 (격자 둘레 한 칸은 비워 둔다). 크기가 자리마다 다른 것(벽 · 들보 · 난간)은
 * 무늬 한 장(_TILE)을 이어 깔고, 상태(열림 · 새 · 바늘 …)는 덧그림을 얹는다.
 */
import type { Grid } from './grid.ts';

// ───────────────────────── 뚜껑문 ─────────────────────────

/**
 * 닫힌 뚜껑문 본 (18×13): 왼쪽 3 열 · 오른쪽 4 열은 틀, 3~13 열(널빤지 한 장 + 틈)을 되풀이하고,
 * 5~9 줄(널 결)을 되풀이한다. 오른쪽 · 아래 틈으로 아래층 빛(g · G)이 샌다.
 */
export const HATCH: Grid = [
  '..................',
  '..................',
  '.hhhhhhhhhhhhhhhh.',
  '.hAAAAAAAAAAAAAAs.',
  '.hAssssssssssssAs.',
  '.hAuWWWWWWWWwvgAs.',
  '.hAuWWWwwWWWwvgAs.',
  '.hAuWWWWWWWWwvgAs.',
  '.hAuWWWWWWWWwvgAs.',
  '.hAuWwwWWWWWwvgAs.',
  '.hAGGGGGGGGGGGGAs.',
  '.hAAAAAAAAAAAAAAs.',
  '.ssssssssssssssss.',
];
/** 쇠 경첩 (7×3) · 손잡이 고리 (6×4) */
export const HINGE: Grid = [
  'iiiiiiM',
  'MMzMMzm',
  'mmmmmmz',
];
export const RING: Grid = [
  '.iMMm.',
  'iz..zm',
  'Mz..zm',
  '.mmzz.',
];

/**
 * 열린 뚜껑문 (48×78): 세워 둔 뚜껑(밑면 B) · 구멍 안 맞은편 벽(위는 깜깜 1, 아래로 갈수록 아래층 불빛 5 · 6) · 사다리 끝(K k).
 */
export const HATCH_OPEN: Grid = [
  '................................................',
  '................................................',
  '....lllllllllllllllllllllllllllllllllllllllb....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBBbBBBlBBBBBBBBBlBBBBBBbBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBbbBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBbBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBbbBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhbn....',
  '....lAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAan....',
  '....laaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaasn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBBBbBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBbBBBBlBBBBBBBBBlBBBBBBBBBlBBBbBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBbBBBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lBBBBBBBBBlBBBBBBBBBlBBBBBBBBBlBBBBBBBbn....',
  '....lbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbn....',
  '....nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn....',
  '.hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh.',
  '.hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAs.',
  '.hAssssssssssssssssssssssssssssssssssssssssssAs.',
  '.hAs1111111111uKk1111111111111uKk111111111111As.',
  '.hAs1111111111uKk1111111111111uKk111111111111As.',
  '.hAs1111111111uKk1111111111111uKk111111111111As.',
  '.hAs1111111111uKKKKKKKKKKKKKKKKKk111111111111As.',
  '.hAs1111111111uKkkkkkkkkkkkkkkuKk111111111111As.',
  '.hAs1111111111uKk1111111111111uKk111111111111As.',
  '.hAs1111111111uKk1111111111111uKk111111111111As.',
  '.hAs2222222222uKk2222222222222uKk222222222222As.',
  '.hAs2222222222uKk2222222222222uKk222222222222As.',
  '.hAs2222222222uKk2222222222222uKk222222222222As.',
  '.hAs2222222222uKKKKKKKKKKKKKKKKKk222222222222As.',
  '.hAs2222222222uKkkkkkkkkkkkkkkuKk222222222222As.',
  '.hAs2222222222uKk2222222222222uKk222222222222As.',
  '.hAs3333333333uKk3333333333333uKk333333333333As.',
  '.hAs3333333333uKk3333333333333uKk333333333333As.',
  '.hAs3333333333uKk3333333333333uKk333333333333As.',
  '.hAs3333333333uKk3333333333333uKk333333333333As.',
  '.hAs3333333333uKKKKKKKKKKKKKKKKKk333333333333As.',
  '.hAs3333333333uKkkkkkkkkkkkkkkuKk333333333333As.',
  '.hAs4444444444uKk4444444444444uKk444444444444As.',
  '.hAs4444444444uKk4444444444444uKk444444444444As.',
  '.hAs4444444444uKk4444444444444uKk444444444444As.',
  '.hAs4444444444uKk4444444444444uKk444444444444As.',
  '.hAs4444444444uKk4444444444444uKk444444444444As.',
  '.hAs4444444444uKKKKKKKKKKKKKKKKKk444444444444As.',
  '.hAs4444444444uKkkkkkkkkkkkkkkuKk444444444444As.',
  '.hAs5555555555uKk5555555555555uKk555555555555As.',
  '.hAs5555555555uKk5555555555555uKk555555555555As.',
  '.hAs5555555555uKk5555555555555uKk555555555555As.',
  '.hAs5555555555uKk5555555555555uKk555555555555As.',
  '.hAs5555555555uKk5555555555555uKk555555555555As.',
  '.hAs5555555555uKKKKKKKKKKKKKKKKKk555555555555As.',
  '.hAs6666666666uKkkkkkkkkkkkkkkuKk666666666666As.',
  '.hAs6666666666uKk6666666666666uKk666666666666As.',
  '.hAs6666666666uKk6666666666666uKk666666666666As.',
  '.hAs6666666666uKk6666666666666uKk666666666666As.',
  '.hAs6666666666uKk6666666666666uKk666666666666As.',
  '.hAs6666666666uKk6666666666666uKk666666666666As.',
  '.hAGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGAs.',
  '.hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAs.',
  '.ssssssssssssssssssssssssssssssssssssssssssssss.',
  '................................................',
  '................................................',
  '................................................',
];

// ───────────────────────── 뻐꾸기시계 (24×48) ─────────────────────────

/** 뻐꾸기시계 (live: 추 · 바늘 없이): 나뭇잎 처마 박공 지붕 · 조각 몸통 · 작은 문 · 시계판(가운데 12, 23) · 사슬 · 솔방울 추 */
export const CUCKOO: Grid = [
  '...........hh...........',
  '..........hAAa..........',
  '.........hAAAAa.........',
  '........hAAhAAAa........',
  '.......hAAhAAAAAa.......',
  '......hAAhAAAAhAAa......',
  '.....hAAhAAAAhAAAAa.....',
  '....hAAhAAAAhAAAAAAa....',
  '...hAAhAAAAhAAAAAAAAa...',
  '..hAAhAAAAhAAAAAAAAAAa..',
  '.lBBlBBlBBlBBlBBlBBlBBb.',
  '..bnbbnbbnbbnbbnbbnbbn..',
  '....uWWWWvvvvvvWWWWw....',
  '....uWWWWvuWWwvWWWWw....',
  '....uWWWWvuWCwvWWWWw....',
  '....uWWWWvwwwwvWWWWw....',
  '....uWWWWvvvvvvWWWWw....',
  '....uWwWWWWWWWWWWwWw....',
  '....uWWWWCCCCCWWWWWw....',
  '....uWWWCPPPPPcWWWWw....',
  '....uWWCPPPXPPPcWWWw....',
  '....uWCPPPPPPPPPcWWw....',
  '....uWCPPPPPPPPPcWWw....',
  '....uWCPXPPPPPXPcWWw....',
  '....uWCPPPPPPPPPcWWw....',
  '....uWCPPPPPPPPPcWWw....',
  '....uWWcPPPXPPPjWWWw....',
  '....uWWWcPPPPPjWWWWw....',
  '....uWWWWcjjjjWWWWWw....',
  '....uWwWWWWWWWWWWwWw....',
  '....wwwwwwwwwwwwwwwv....',
  '....vvvvvvvvvvvvvvvv....',
  '........M.......M.......',
  '........M.......M.......',
  '........M.......M.......',
  '........M.......M.......',
  '........M.......M.......',
  '........M.......M.......',
  '........M......kKk......',
  '........M.....kKkKk.....',
  '........M.....KkKkk.....',
  '.......kKk....kKkKk.....',
  '......kKkKk...kKkKk.....',
  '......KkKkk....kKk......',
  '......kKkKk.....k.......',
  '......kKkKk.............',
  '.......kKk..............',
  '........k...............',
];
/** live 가 아닐 때 얹는 추 막대 · 추 · 바늘 (8시 20분쯤) */
export const CUCKOO_STILL: Grid = [
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '..........X.............',
  '...........X............',
  '............XXX.........',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '............M...........',
  '............M...........',
  '............M...........',
  '............M...........',
  '............M...........',
  '............M...........',
  '............M...........',
  '............M...........',
  '...........CCC..........',
  '..........CGCCc.........',
  '..........CCCcc.........',
  '...........ccc..........',
];
/** bird: 문이 활짝 (문짝은 왼쪽으로 젖혀짐) · 뻐꾸기가 날개를 펴고 부리를 벌려 운다 */
export const CUCKOO_BIRD: Grid = [
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '.....................4..',
  '.......1.....33.....4...',
  '......11....3223..4.....',
  '......111..323X2155.....',
  '.......1111222223.......',
  '.......hhX2222223.......',
  '.......hhXXX222XX.......',
  '.......hhXXXXXXXX.......',
  '.......hhXXXXXXXX.......',
  '.......hhXXXXXXXX.......',
];

// ───────────────────────── 크리스마스 장식 상자 (48×34) ─────────────────────────

/** 열린 골판지 상자: 뒤로 젖힌 덮개(윗면 3~6 줄) · 어두운 속 · 앞면(17~31 줄) · 오른쪽 옆면(40~43 열) */
export const XMASBOX: Grid = [
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '...qQqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqk.......',
  '...qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkk......',
  '...qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkkk.....',
  '...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....',
  '...qvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvkkkkk....',
  '...qvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvkkkkk....',
  '...qvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvkkkkk....',
  '...qvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvkkkkk....',
  '...qvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvkkkkk....',
  '...qvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvkkkkk....',
  '...qvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvkkkkk....',
  '...qvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvkkkkk....',
  '...QqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqkkkkK...',
  '...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkk....',
  '...qKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkkkk....',
  '...qKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkkkk....',
  '...qKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkkkk....',
  '...qKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkkkk....',
  '...qKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkkkk....',
  '...qKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkkkk....',
  '...qKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkkkk....',
  '...qKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkkkk....',
  '...qKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkkkk....',
  '...qKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkkkk....',
  '...qKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkkkk....',
  '...qKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKKkkkk....',
  '...qKKkKKkKKkKKkKKkKKkKKkKKkKKkKKkKKkKKKkkkk....',
  '...kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkx....',
  '...xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx....',
  '................................................',
];
/** 장식 공 넷 (빨강 · 초록 · 금 · 파랑, 5×5) */
export const BALL_RED: Grid = ['.gCc.', 'gGCCc', 'CCCcc', 'cCccj', '.cjj.'];
export const BALL_GREEN: Grid = ['.hAa.', 'hhAAa', 'AAAaa', 'aAaas', '.ass.'];
export const BALL_GOLD: Grid = ['.iMm.', 'iIMMm', 'MMMmm', 'mMmmz', '.mzz.'];
export const BALL_BLUE: Grid = ['.lBb.', 'llBBb', 'BBBbb', 'bBbbn', '.bnn.'];
/** 빨간 리본 두른 쪽지 (14×8) */
export const XMAS_TAG: Grid = [
  'oPPPPPRRPPPPPp',
  'PPPPPPRRPPPPPp',
  'PPPPPPRRPPPPPp',
  'RRRRRRRRRRRRRR',
  'rrrrrrRRrrrrrr',
  'PPPPPPRRPPPPPp',
  'PPPPPPRRPPPPPp',
  'pppppprrpppppy',
];
/** 상자 밖으로 흘러 바닥에 고인 반짝이 줄 (8×18) */
export const TINSEL: Grid = [
  '..12....',
  '..21....',
  '.12.....',
  '.21.....',
  '..12....',
  '...21...',
  '...12...',
  '..21....',
  '..12....',
  '.21.....',
  '.12.....',
  '..21....',
  '...12...',
  '...21...',
  '..12....',
  '.21.....',
  '1232123.',
  '23212321',
];

// ───────────────────────── 꿀사탕 · 선풍기 ─────────────────────────

/** 꿀사탕 한 알 (18×7): 호박색 알맹이 · 양 끝을 비튼 주름 껍질 */
export const HONEYCANDY: Grid = [
  'oP.....gGGc.....Pp',
  'PoP...gGOGCc...PpP',
  'PPpPpgGGGCCCcpPpPp',
  'oPPpyGCCCCCcjypPpy',
  'PpPPpcCCCCccjpPpPp',
  'pPp...cCCccj...ppy',
  'pp.....cjjj.....py',
];

/** 선풍기 머리 (19×19): 크림 테 · 어두운 속 · 날개 넷 (B) · 망 살 · 빨간 가운데 */
export const FAN_HEAD: Grid = [
  '......iiiiiii......',
  '....iiMMMMMMMmm....',
  '...iMMAAAMAAAMMm...',
  '..iMAABBAMABBAAMm..',
  '.iMABBBBAMABBBBAMm.',
  '.iMABlBBAMABlBBAMm.',
  'iMAAABBBAMABBBAAAMm',
  'iMAAAAAAAMAAAAAAAMm',
  'iMAAAAAA121AAAAAAMm',
  'iMMMMMMM222MMMMMMMm',
  'iMAAAAAA121AAAAAAMm',
  'iMAAAAAAAMAAAAAAAMm',
  'iMAAABBBAMABBBAAAMm',
  '.iMABlBBAMABlBBAMm.',
  '.iMABBBBAMABBBBAMm.',
  '..iMAABBAMABBAAMm..',
  '...iMMAAAMAAAMMm...',
  '....mmMMMMMMMmm....',
  '......mmmmmmm......',
];
/** 선풍기 목 한 칸 (3×1, 되풀이) · 받침 (20×11: 윗면 4 줄 · 피아노 단추 앞면 · 오른쪽 옆면 3 열) */
export const FAN_NECK: Grid = ['iMm'];
export const FAN_BASE: Grid = [
  'gGgggggggggggggggc..',
  'gggggggggggggggggcc.',
  'gggggggggggggggggccc',
  'gggggggggggggggggccc',
  'CCCCCCCCCCCCCCCCCccc',
  'CPPCPPC11CPPCCCCCccc',
  'CPPCPPC11CPPCCCCCccc',
  'CppCppCppCppCCCCCccc',
  'CCCCCCCCCCCCCCCCCccc',
  'cccccccccccccccccjjj',
  'jjjjjjjjjjjjjjjjjjj.',
];

// ───────────────────────── 세발자전거 (48×34) ─────────────────────────

/** 큰 앞바퀴 (17×17): 검은 고무 · 쇠 테 · 바큇살 사이로 바닥이 보인다 · 빨간 축 */
export const WHEEL_BIG: Grid = [
  '.....AAAAAAA.....',
  '...AAhhhhhAAAA...',
  '..AhhAAAAAAAAsA..',
  '.AhAAMMMMMMMAAsA.',
  '.AhAM..i.i..MAsA.',
  'AhAM.i..i..i.MAsA',
  'AhAM..i.i.i..MAsA',
  'AhAMiii.i.iiiMAsA',
  'AhAM...iCi...MAsA',
  'AhAMiii.i.iiiMAsA',
  'AhAM..i.i.i..MAsA',
  'AhAM.i..i..i.MAsA',
  '.AhAM..i.i..MAsA.',
  '.AhAAMMMMMMMAAsA.',
  '..AaaAAAAAAaasA..',
  '...AAaaaaaaAAA...',
  '.....sssssss.....',
];
/** 작은 뒷바퀴 (11×11) */
export const WHEEL_SMALL: Grid = [
  '...AAAAA...',
  '.AAhhhAAA..',
  '.AhMMMMMAs.',
  'AhM.i.i.MAs',
  'AhMii.iiMAs',
  'AhM..C..MAs',
  'AhMii.iiMAs',
  'AhM.i.i.MAs',
  '.AsMMMMMas.',
  '..aAAAAAa..',
  '...sssss...',
];
/** 앞 포크 (9×19): 손잡이에서 앞바퀴 축까지 비스듬히 (1 녹) */
export const TRIKE_FORK: Grid = [
  '......gCc',
  '......gCc',
  '......gCc',
  '......gCc',
  '......gCc',
  '.....gCc.',
  '.....g1c.',
  '.....gCc.',
  '....gCc..',
  '....gCc..',
  '....gCc..',
  '...gCc...',
  '...gCc...',
  '...gCc...',
  '..gCc....',
  '..gCc....',
  '..g1c....',
  '.gCc.....',
  '.gCc.....',
];
/** 몸통 관 (20×13): 포크 가운데에서 뒷바퀴 축 쪽으로 */
export const TRIKE_TUBE: Grid = [
  '....................',
  '.gCC................',
  '.cgCC...............',
  '...cgCC.............',
  '.....cgCC...........',
  '......cg1C..........',
  '........cgCC........',
  '.........cgCC.......',
  '...........cgCC.....',
  '............cgCC....',
  '..............cgCC..',
  '...............cgCCc',
  '.................cc.',
];
/** 뒤 발판 (17×3) · 안장 기둥 (2×6) · 안장 (11×3) · 핸들과 바랜 술 (16×5) */
export const TRIKE_STEP: Grid = [
  'gggggggggg1ggggCc',
  'CCCCCCCCCCCCCCCCc',
  'ccccccccccccccccj',
];
export const TRIKE_POST: Grid = ['Mm', 'Mm', 'Mm', 'Mm', 'Mm', 'Mm'];
export const TRIKE_SEAT: Grid = [
  '..uuuuuuu..',
  '.uWWWWWWWWw',
  'vwwwwwwwwwv',
];
export const TRIKE_BAR: Grid = [
  'oPPiiiiiiiiiioPp',
  'pPpMMMMMMMMMMpPy',
  '234..........234',
  '2.4..........2.4',
  '2............2..',
];

// ───────────────────────── 돗자리 · 천 씌운 화장대 ─────────────────────────

/** 둘둘 만 돗자리 (48×24): 밝은 윗면 · 엮은 결 · 바랜 초록 테 · 빨간 끈 둘 · 오른쪽 말린 단면 */
export const MAT: Grid = [
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '....lBBggggggAaggggggggggggggggAagggggg..gCCc...',
  '....lBBgGggggAagggGggggggggggggAagggggg.gCcccc..',
  '....BBBCCCCCCAaCCCCCCCCCCCCCCCCAaCCCCCCgCcCCcc..',
  '....BBBCcCCcCAaCcCCcCCcCCcCCcCCAacCCcCCgcCccCc..',
  '....BBBCCCCCCAaCCCCCCCCCCCCCCCCAaCCCCCCgcCjjCc..',
  '....BBbCCcCCcAaCCcCCcCCcCCcCCcCAaCcCCcCgcCjcCc..',
  '....BBbCCCCCCAaCCCCCCCCCCCCCCCCAaCCCCCCgcCcjCc..',
  '....BbbccccccaaccccccccccccccccaaccccccgcCCCcc..',
  '....bbbcjccjcaaccjccjccjccjccjcaacjccjcgccccCc..',
  '....bbnjjjjjjasjjjjjjjjjjjjjjjjasjjjjjj.cCCCcj..',
  '....nnnjjjjjjssjjjjjjjjjjjjjjjjssjjjjjj..cjjj...',
  '................................................',
  '................................................',
];

/** 천 씌운 화장대 (48×64): 거울에 씌운 천 혹 · 밝은 윗면(22~29 줄) · 세로 주름 앞면 · 물결 단 · 짧은 다리 · 오른쪽 옆면 */
export const DRESSER_CLOTH: Grid = [
  '................................................',
  '................................................',
  '....................oooooooo....................',
  '.................oooOOooooooPP..................',
  '...............ooOOOoooooooPPPPp................',
  '..............oOOOooooooooPPPPPPp...............',
  '.............oOOooooooooooPPPPPPpp..............',
  '............oOOoooooooooooPPPPPPPpp.............',
  '............oOooooooooooooPPPPPPPpp.............',
  '...........oOooooooooooooPPPPPPPPppy............',
  '...........oOoooooooooooPPPPPPPPPppy............',
  '...........ooooooooooooPPPPPPPPPPPppy...........',
  '..........ooooooooooPPPPPPPPPPPPPppyy...........',
  '..........oooooooooPPPPPPPPPPPPPpppyy...........',
  '..........ooooooooPPPPPPPPPPPPPPpppyy...........',
  '..........oooooooPPPPPPPPPPPPPPppppyy...........',
  '..........ooooooPPPPPPPPPPPPPPPppppyy...........',
  '..........oooooPPPPPPPPPPPPPPPpppppyy...........',
  '..........ooooPPPPPPPPPPPPPPPPppppyyy...........',
  '...........oooPPPPPPPPPPPPPPPpppppyy............',
  '...........ooPPPPPPPPPPPPPPPppppppyy............',
  '............ooPPPPPPPPPPPPpppppppyy.............',
  '..oOOooooooooooooooooooooooooooooooooooooop.....',
  '..oooooooooooooooooooooooooooooooooooooooopp....',
  '..oooooooooooooooooooooooooooooooooooooooppp....',
  '..oooooooooooooooooooooooooooooooooooooooopppp..',
  '..oooooooooooooooooooooooooooooooooooooooopppp..',
  '..oooooooooooooooooooooooooooooooooooooooopppp..',
  '..oooooooooooooooooooooooooooooooooooooooopppp..',
  '..oooooooooooooooooooooooooooooooooooooooopppp..',
  '..PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpppy..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..oPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpoPPPPPpppp..',
  '..PPpPPpPPpPPpPPpPPpPPpPPpPPpPPpPPpPPpPPpPpppy..',
  '..pp.pp.pp.pp.pp.pp.pp.pp.pp.pp.pp.pp.pp.ppyy...',
  '.....uWv..........................uWv...........',
  '.....uWv..........................uWv...........',
  '.....wvv..........................wvv...........',
  '................................................',
  '................................................',
];
/** 화장대 윗면에 엎어 둔 빈 액자 (15×5): 뒷판이 보인다 */
export const DRESSER_FRAME: Grid = [
  'uuuuuuuuuuuuuuw',
  'uAAAAAAAAAAAAAw',
  'uAAAAAhhAAAAAAw',
  'uaaaaaaaaaaaaaw',
  'wvvvvvvvvvvvvvv',
];

// ───────────────────────── 끈으로 묶은 책 더미 (24×28) ─────────────────────────

/** 맨 위 초록 책(윗면 1~8 줄) · 책등이 앞을 보는 책 넷 (초록 · 겨자 · 파랑 · 빨강, 금박 점) · 오른쪽 옆면. 끈은 따로 */
export const BOOKBUNDLE: Grid = [
  '........................',
  '...44444444444444.......',
  '...444444444444446......',
  '...4555555555555566.....',
  '...45555522555555666....',
  '...45555222255555666....',
  '...45555522555555666....',
  '...45555555555555666....',
  '...66666666666666777....',
  '...55555555555555777....',
  '...51555555555515777....',
  '...55555555555555777....',
  '...66666666666666777....',
  '....BBBBBBBBBBBBBbnnn...',
  '....B1BBBBBBBBB1Bbnnn...',
  '....BBBlllllllBBBbnnn...',
  '....bbbbbbbbbbbbbbnnn...',
  '...AAAAAAAAAAAAAAsss....',
  '...A1AAAAAAAAAA1Asss....',
  '...AAAhhhhhhhhAAAsss....',
  '...aaaaaaaaaaaaaasss....',
  '....CCCCCCCCCCCCCcjjj...',
  '....C1CCCCCCCCC1Ccjjj...',
  '....CCCggggggCCCCcjjj...',
  '....CCCCCCCCCCCCCcjjj...',
  '....ccccccccccccccjjj...',
  '........................',
  '........................',
];
/** 열십자 끈 · 매듭 (15×24, 책 더미 (3, 1)) */
export const BOOK_TWINE: Grid = [
  '.......W.......',
  '......uWw......',
  '.......u.......',
  'uuuuuuuuuuuuuuu',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
  '.......u.......',
];

// ───────────────────────── 우산꽂이 (24×46) ─────────────────────────

/** 바랜 초록 도자기 통 (18×23): 둥근 입구 · 띠 홈 둘 */
export const UMB_POT: Grid = [
  '...lBBBBBBBBBBb...',
  '.lBBnnnnnnnnnnBBb.',
  'lBBnnnnnnnnnnnnBBb',
  'lBBBnnnnnnnnnnBBBb',
  '.lBBBBBBBBBBBBBBb.',
  'llBBBBBBBBBBBBbbbn',
  'llBBBBBBBBBBBBbbbn',
  'llBBBBBBBBBBBBbbbn',
  'lbbbbbbbbbbbbbbbbn',
  'llllllllllllllbbbn',
  'llBBBBBBBBBBBBbbbn',
  'llBBBBBBBBBBBBbbbn',
  'llBBBBBBBBBBBBbbbn',
  'llBBBBBBBBBBBBbbbn',
  'llBBBBBBBBBBBBbbbn',
  'llBBBBBBBBBBBBbbbn',
  'llBBBBBBBBBBBBbbbn',
  'lbbbbbbbbbbbbbbbbn',
  'llllllllllllllbbbn',
  'llBBBBBBBBBBBBbbbn',
  'lBBBBBBBBBBBBBbbbn',
  '.bbbbbbbbbbbbbbbb.',
  '..nnnnnnnnnnnnnn..',
];
/** 남색 우산 (7×30): 굽은 손잡이 · 쇠 대 · 접힌 천 · 여밈 끈 */
export const UMB_NAVY: Grid = [
  '..uWw..',
  '.w...W.',
  'v....W.',
  '.....M.',
  '.....M.',
  '.....M.',
  '....hAa',
  '....hAa',
  '...hAAa',
  '...hAAa',
  '...hAas',
  '..hAAAa',
  '..hAaAa',
  '..hAAAa',
  '..hAaAa',
  '..PPPPp',
  '..hAAAa',
  '..hAaAa',
  '..hAAAa',
  '..hAaAa',
  '..hAAAa',
  '..hAaAa',
  '..hAAAa',
  '..hAaAa',
  '..hAAAa',
  '..hAaAa',
  '..hAAAa',
  '..hAaAa',
  '..hAAAa',
  '..hAaAa',
];
/** 빨간 줄무늬 우산 (7×26): 동그란 나무 손잡이 · 크림 줄 */
export const UMB_RED: Grid = [
  '.uWWw..',
  '.WWWv..',
  '..vv...',
  '..Mm...',
  '..Mm...',
  '.gCCc..',
  '.gCCc..',
  'gCCCcc.',
  'gPPPPp.',
  'gCCCcc.',
  'gCCCcc.',
  'gCCCcc.',
  'gPPPPp.',
  'gCCCcc.',
  'gCCCcc.',
  'gCCCcc.',
  'gPPPPp.',
  'gCCCcc.',
  'gCCCcc.',
  'gCCCcc.',
  'gPPPPp.',
  'gCCCcc.',
  'gCCCcc.',
  'gCCCcc.',
  'gCCCcc.',
  'gCCCcc.',
];

// ───────────────────────── 반짇고리 · 쥐덫 · 페인트 통 (24×24) ─────────────────────────

/** 나무 반짇고리: 손잡이 · 밝은 뚜껑 윗면(6~10 줄) · 틈 · 금빛 걸쇠 · 앞면(13~21 줄) · 옆면(19~21 열) */
export const SEWBOX: Grid = [
  '........................',
  '........................',
  '........................',
  '......vWWWWWv...........',
  '.....v.......v..........',
  '.....v.......v..........',
  '.uuuuuuuuuuuuuuuuuuw....',
  '.uUuuuuuuuuuuuuuuuuww...',
  '.uuuuuWWuuuuuuuuuuuwww..',
  '.uuuuuuuuuuuuWWWuuuwww..',
  '.uuWWuuuuuuuuuuuuuuwww..',
  '.wwwwwwwwwwwwwwwwwwwww..',
  '.vvvvvvvvvvvvvvvvvvvvv..',
  '.WWWWWWWWCCCCWWWWWWwww..',
  '.WWWWWWWWCGCcWWWWWWwww..',
  '.WWWWWWWWccccWWWWWWwww..',
  '.WWWWWWWWWWWWWWWWWWwww..',
  '.WWwwwWWWWWWWWwwWWWwww..',
  '.WWWWWWWWWWWWWWWWWWwww..',
  '.WWWWWWWWWWWWWWWWWWwww..',
  '.WWWWWWWWWWWWWWWWWWwww..',
  '.wwwwwwwwwwwwwwwwwwvvv..',
  '.vvvvvvvvvvvvvvvvvvvvv..',
  '........................',
];
/** 틈으로 빠져나온 붉은 실 (5×12, 반짇고리 (0, 12)) · 뚜껑에 꽂힌 바늘 (6×3) */
export const SEW_THREAD: Grid = [
  '...A.',
  '..A..',
  '..A..',
  '.A...',
  '.A...',
  'A....',
  'A....',
  'A....',
  '.A...',
  '.Aa..',
  '..aa.',
  '.....',
];
export const SEW_NEEDLE: Grid = [
  '....Ii',
  '..IM..',
  'IM....',
];

/** 쥐덫: 밝은 나무 윗면(13~18 줄) · ㄷ자 쇠틀 · 미끼 치즈 · 용수철 · 앞면(19~21 줄) · 옆면 */
export const MOUSETRAP: Grid = [
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '........................',
  '...uuuuuuuuuuuuuuuuw....',
  '...uMMMMMMMMMMuuuuuww...',
  '...uMuuuuuuuuMuIiuuww...',
  '...uMuuuGCCuuMuiIuuww...',
  '...uMuuuCCcuuMuuuuuww...',
  '...uMMMMMMMMMMuuuuuww...',
  '...WWWWWWWWWWWWWWWWww...',
  '...WWWWWWWWWWWWWWWWww...',
  '...WWWWWWWWWWWWWWWWww...',
  '...vvvvvvvvvvvvvvvvvv...',
  '........................',
];

/** 페인트 통: 뚜껑 위에 가로 놓인 붓 · 마른 흰 페인트 자국 · 파란 상표 띠 · 원기둥 명암 */
export const PAINTCAN: Grid = [
  '........................',
  '........................',
  '........................',
  '........................',
  '.uWWWWWWWWWWWWMMPPP.....',
  '.wwwwwwwwwwwwwmmPpp.....',
  '.....iiiiiiiiiiii.......',
  '....iOOOOOOOOOOOOm......',
  '....iOOOOOOOOOOOOm......',
  '....iOOOMMMOOMMmmz......',
  '....iOOOMMMOOMMmmz......',
  '....iOOOMMMOOMMmmz......',
  '....iIOOMMMOMMMmmz......',
  '....hAOAAAAAAAAaas......',
  '....hAOAAAAAAAAaas......',
  '....hAAPPPPPPAAaas......',
  '....hAAAAAAAAAAaas......',
  '....aaaaaaaaaaaass......',
  '....iIMMMMMMMMMmmz......',
  '....iIMMMMMMMMMmmz......',
  '....iIMMMMMMMMMmmz......',
  '....mmmmmmmmmmmmzz......',
  '.....zzzzzzzzzzzz.......',
  '........................',
];

// ───────────────────────── 거미줄 (24×24, 왼쪽 위 구석) ─────────────────────────

/** 구석에서 퍼지는 실 다섯 가닥 · 처진 둥근 실 넷 */
export const COBWEB: Grid = [
  'PPPPPPPPPPPPPPPPPPPPPPP.',
  'PPPP..P....P....P....P..',
  'PPP.PPP....P....P....P..',
  'PP.P.P.P..P....P.....P..',
  'P.P.P....PP....P....P...',
  'P.PP.P...P.PPP.P....P...',
  'PPP...P..P....PP....P...',
  'P..P...PP.....P.PPPP....',
  'P..P...PP....P.....PP...',
  'P...PPP..P..P.....P.....',
  'P..PP.....PP.....P......',
  'PPP..P.....P.....P......',
  'P....P....P.P...P.......',
  'P....P...P...P.P........',
  'P.....PPP.....PP........',
  'P...PPP.......PP........',
  'PPPP...P.....P..P.......',
  'P......P...PP...........',
  'P......P..P.............',
  'P......PPP..............',
  'P...PPP.P...............',
  'PPPP....................',
  'P.......................',
  '........................',
];
/** 거미 한 마리 (4×5) */
export const SPIDER: Grid = [
  '.p..',
  'x..x',
  '.XX.',
  '.XX.',
  'x..x',
];

// ───────────────────────── 낡은 의자 (24×46) ─────────────────────────

/** 등받이(위 가로대 · 가운데 가로대 · 살 둘) · 밝은 앉는 판 윗면(29~36 줄) · 앞면(37~40 줄) · 옆면 · 다리 */
export const CHAIR_OLD: Grid = [
  '........................',
  '........................',
  '....uuuuuuuuuuuuuuw.....',
  '....uWWWWWWWWWWWWWwv....',
  '....wwwwwwwwwwwwwwvv....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWvuuuuuuuuuuWv.....',
  '....uWvwwwwwwwwwuWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..uw.uw..uWv.....',
  '....uWv..ww.ww..uWv.....',
  '..uuuuuuuuuuuuuuuuuw....',
  '..uUuuuuuuuuuuuuuuuww...',
  '..uuuuWWuuuuuuuWWuuwww..',
  '..uuuuuuuuuuuuuuuuuwww..',
  '..uuuuuuuuWWWuuuuuuwww..',
  '..uuWWuuuuuuuuuuuuuwww..',
  '..uuuuuuuuuuuuuWWuuwww..',
  '..wwwwwwwwwwwwwwwwwwww..',
  '..WWWWWWWWWWWWWWWWWwww..',
  '..WWWWWWWWWWWWWWWWWwww..',
  '..WWWWWWWWWWWWWWWWWwww..',
  '..WWWWWWWWWWWWWWWWWwww..',
  '..vvvvvvvvvvvvvvvvvvvv..',
  '...uWv..........wvv.....',
  '...uWv..........wvv.....',
  '...wvv..........vvv.....',
  '........................',
];
/** 등받이에 붙은 쪽지 「두고 가는 짐」 (10×8) */
export const CHAIR_NOTE: Grid = [
  '.11.......',
  'oPPPPPPPPp',
  'PXXPXXXPPp',
  'PPPPPPPPPp',
  'PXXXPXXPPp',
  'PPPPPPPPPp',
  'PXXPPPPPPp',
  'pppppppppy',
];

// ───────────────────────── 다락 뒷벽 · 들보 · 난간 (자리마다 폭이 다르다) ─────────────────────────

/**
 * 다락 뒷벽 무늬 (40×84, 가로로 이어 깐다 · 키가 작으면 아래쪽 줄만): 비스듬한 천장 널(위로 갈수록 멀어 어둡게, 6 줄마다 이음매) ·
 * 서까래(16~20 열) · 도리(44~47 줄) · 세로 널빤지 벽(8 칸 널, 띄엄띄엄 옹이) · 걸레받이.
 */
export const WALL_TILE: Grid = [
  'jjjjjjjjjjjjjjjjhAAAsjjjjjjjjjjjjjjjjjjj',
  'jjjjjjjjjjjjjjjjhAAAsjjjjjjjjjjjjjjjjjjj',
  'jjjjjjjjjjjjjjjjhAAAsjjjjjjjjjjjjjjjjjjj',
  'cccccccccccccccchAAAsccccccccccccccccccc',
  'ccccccccjccccccchAAAsccccccccccccccccccc',
  'cccccccccccccccchAAAsccccccccccccccccccc',
  'cccccccccccccccchAAAsccccccccccccccccccc',
  'cccccccccccccccchAAAsccccccccccccccccccc',
  'jjjjjjjjjjjjjjjjhAAAsjjjjjjjjjjjjjjjjjjj',
  'cccccccccccccccchAAAsccccccccccccccccccc',
  'cccccccccccccccchAAAscccccccccccjccccccc',
  'cccccccccccccccchAAAsccccccccccccccccccc',
  'cccccccccccccccchAAAsccccccccccccccccccc',
  'cccccccccccccccchAAAsccccccccccccccccccc',
  'cccccccccccccccchAAAsccccccccccccccccccc',
  'CCCCCCCCCCCCCCCChAAAsCCCCCCCCCCCCCCCCCCC',
  'CCCCCCcCCCCCCCCChAAAsCCCCCCCCCCCCCCCCCCC',
  'CCCCCCcCCCCCCCCChAAAsCCCCCCCCCCCCCCCCCCC',
  'CCCCCCcCCCCCCCCChAAAsCCCCCCCCCCCCCCCCCCC',
  'CCCCCCcCCCCCCCCChAAAsCCCCCCCCCCCCCCCCCCC',
  'CCCCCCcCCCCCCCCChAAAsCCCCCCCCCCCCCCCCCCC',
  'cccccccccccccccchAAAsccccccccccccccccccc',
  'CCCCCCCCCCCCCCCChAAAsCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCChAAAsCCCCCCCCCCCcCCCCCCC',
  'CCCCCCCCCCCCCCCChAAAsCCCCCCCCCCCcCCCCCCC',
  'CCCCCCCCCCCCCCCChAAAsCCCCCCCCCCCcCCCCCCC',
  'CCCCCCCCCCCCCCCChAAAsCCCCCCCCCCCcCCCCCCC',
  'cccccccccccccccchAAAsccccccccccccccccccc',
  'gggggggggggggggghAAAsggggggggggggggggggg',
  'gggggggggggggggghAAAsggggggggggggggggggg',
  'gggggggggggggggghAAAsggggggggggggggggggg',
  'gggggggggggggggghAAAsggggggggggggggggggg',
  'gggggggggggggggghAAAsggggggggggggggggggg',
  'CCCCCCCCCCCCCCCChAAAsCCCCCCCCCCCCCCCCCCC',
  'gggggggggggggggghAAAAsgggggggggggggggggg',
  'ggggcggggggggggghAAAAsgggggggggggggggggg',
  'ggggcggggggggggghAAAAsgggggggggggggggggg',
  'ggggcggggggggggghAAAAsgggggggggggggggggg',
  'ggggcggggggggggghAAAAsgggggggggggggggggg',
  'CCCCCCCCCCCCCCCChAAAAsCCCCCCCCCCCCCCCCCC',
  'gggggggggggggggghAAAAsgggggggggggggggggg',
  'gggggggggggggggghAAAAsgggggggggggggggggg',
  'gggggggggggggggghAAAAsgggggggggggggggggg',
  'cccccccccccccccchaaaascccccccccccccccccc',
  'hhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh',
  'AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA',
  'AAAaaAAAAAAAAAAAAAAAAAAAAAaaaAAAAAAAAAAA',
  'ssssssssssssssssssssssssssssssssssssssss',
  'vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWvWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWvvwWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWwWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWvWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWvvwWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWwWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWvW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWvvw',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWwW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWvWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWvvwWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWwWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWWwuWWWWWW',
  'wwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww',
  'llllllllllllllllllllllllllllllllllllllll',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
  'BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB',
  'nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn',
];

/**
 * 둥근 박공 창 (35×36): 크림 나무 테(왼쪽 위 Q 밝음 · 오른쪽 아래 q · T) · 밤하늘(위 z → 아래 i) · 초승달 O · 별 1 ·
 * 나뭇가지 그림자 2 · 십자 창살(e 밝음 · t 그늘) · 아래 창턱.
 */
export const WALL_WINDOW: Grid = [
  '.............QQQQQQQQq.............',
  '..........QQQQQQQQqqqqqqq..........',
  '........QQQQQzzzzezzzzqqqqq........',
  '.......QQQQzzzzzzezzzzzzqqqq.......',
  '......QQQzzzzz1zzezzzzzzzzqqq......',
  '.....QQQzzzzzz1zzezzzzzzzzzqqq.....',
  '....QQQmmmmmmmmmmemmmm1mmmmmqqq....',
  '...QQQmmmmOOOmmmmemmmmmmmmmmmqqq...',
  '...QQmmmmOOmmmmmmemmmmmmmmmmmmqq...',
  '..QQmmmmmOmmmmmmmemmmmmmmm1mmmmqq..',
  '..QQmmmmmOmmmmmmmemmmmmmmmmmmmmqq..',
  '.QQmmmmmmOOmmmmmmemmmmmmmmmmmmmmqq.',
  '.QQmmmmmmmOOOmmmmemmmmmmmmmmmmmmqq.',
  '.QQMMMMMMMMMMMMMMeMMMMMMMMMM1MMMqq.',
  '.QQMMMM1MMMMMMMMMeMMMMMMMMMMMMMMqq.',
  '.QQMMMMMMMMMMMMMMeMMMMMMMMMMMMMMqq.',
  '.QQeeeeeeeeeeeeeeeeeeeeeeeeeeeeeqq.',
  '.TTttttttttttttttettttttttttttttqq.',
  '.TTMMMMMMMMMMMMMMeMMMMMMMMMMMMMMqq.',
  '.TTMMMMMMMMMMMMMMeMMMMMMMMMMMMMMqq.',
  '.TTMMMMMMMMMMMMMMeMMMMMMMMMMMMM2qq.',
  '.TTMMMMMMMMMMMMMMeMMMMMMMMMMM22Mqq.',
  '..TTiiiiiiiiiiiiieiiiiiiiii22iiqq..',
  '..TTiiiiiiiiiiiiieiiiiiiii2iiiiqq..',
  '...TTiiiiiiiiiiiieiiiiiii2iiiiqq...',
  '...TTTiiiiiiiiiiieiiiiiiiii2iqqq...',
  '....TTTiiiiiiiiiieiiiiiiiiiiqqq....',
  '.....TTTiiiiiiiiieiiiiiiiiiqqq.....',
  '......TTTiiiiiiiieiiiiiiiiqqq......',
  '.......TTTTiiiiiieiiiiiiqqqq.......',
  '........TTTTTiiiieiiiiqqqqq........',
  '..........TTTTTTTqqqqqqqq..........',
  '.............qqqqqqqqq.............',
  'eeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee',
  'TTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTt',
  'tttttttttttttttttttttttttttttttttts',
];

/** 들보 몸통 무늬 (32×10): 달빛 받은 윗면 · 앞면 · 못 · 갈라진 금 · 아래 그늘 */
export const BEAM_TILE: Grid = [
  'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
  'gggggggggggggggggggggggggggggggg',
  'gggggggggGgggggggggggggggggggggg',
  'cccccccccccccccccccccccccccccccc',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCiCCCCCCCCCCCCcccccccCCCCCCC',
  'CCCCCzCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCcccCCCCCCCCCCCCCcccC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj',
];
/** 들보 오른쪽 끝에 처진 거미줄 · 거미 (16×13, 몸통 아래) */
export const BEAM_WEB: Grid = [
  'PP...P....P...PP',
  '..PP..P...P..P..',
  '....PP.P..P.P...',
  '......PPPPPP....',
  '.......P..P.....',
  '.......P..P.....',
  '........P.P.....',
  '........PP......',
  '.........P......',
  '.........P......',
  '.........P......',
  '........XX......',
  '.......x..x.....',
];

/** 난간 무늬 (8×28, 가로로 이어 깐다): 둥근 손잡이 · 살 하나 · 아래 가름대 */
export const RAIL_TILE: Grid = [
  '........',
  'uuuuuuuu',
  'uuuuuuuu',
  'WWWWWWWW',
  'WWwWWWWW',
  'wwwwwwww',
  'vvvvvvvv',
  '..vvv...',
  '..uWw...',
  '..uWw...',
  '..uWw...',
  '..uWw...',
  '..uWw...',
  '..uWw...',
  '..uWw...',
  '..uWw...',
  '..uWw...',
  '..uWw...',
  '..uWw...',
  '..uWw...',
  '..uWw...',
  '..uWw...',
  '..wwv...',
  'uuuuuuuu',
  'WWWWWWWW',
  'WWWWWWWW',
  'vvvvvvvv',
  '........',
];
/** 손잡이에 걸린 노란 털실 한 가닥 (4×20) */
export const RAIL_YARN: Grid = [
  'Gg..',
  '.C..',
  '.C..',
  '..C.',
  '..C.',
  '..c.',
  '.C..',
  '.C..',
  '.c..',
  '..C.',
  '..C.',
  '..c.',
  '.C..',
  '.C..',
  '.c..',
  '..C.',
  '..c.',
  '.Cc.',
  '.cc.',
  '..j.',
];
