/**
 * 책상 위 소품 (houseProps.ts, 장난감 눈높이) 의 손찍기 격자. 한 칸씩 직접 찍었다 (견본 화풍: 둥근 실루엣 · 3단 명암 · 왼쪽 위 빛).
 * 글자는 소품마다 팔레트 한 줄(houseProps.ts 의 DPAL)로 칠한다. 이 파일 안 글자의 뜻:
 *   G g C c j 주된 색   . h A a s 둘째 색   . l B b n 셋째 색   . 4 5 6 7 · . S s R r · . E e D d 넷째 · 다섯째 · 여섯째 색
 *   O o P p y 종이       I i M m z 쇠 · 유리 · 화면   . u W w v 나무 · 깎은 나무   . e T t . 테이프
 *   X 먹 (연필심 · 글씨) · 1~9 포인트 색 (팔레트마다 다름)
 * 큰 소품은 조각(본 · 무늬)을 손으로 찍고 houseProps.ts 에서 자리에 놓거나 되풀이해 늘인다 (9-조각 · 이어 깔기).
 * 글씨(책 제목 · 날짜 · 점수 · 숫자)는 비워 두고 그릴 때 글씨 격자(glyphs.ts)를 얹는다.
 */
import type { Grid } from './grid.ts';

/**
 * 책 한 권 (15 폭): 0~2 줄 윗면(종이 · 표지 가장자리), 3 줄부터 책등, 6 줄 위 금띠, 7 줄을 되풀이해 키를 맞추고,
 * 8 줄 아래 금띠, 마지막 줄 바닥 그늘. 오른쪽 2 열은 책 사이 틈. 얇은 책(7 폭)은 가운데 열을 줄인다.
 */
export const BOOK_SPINE: Grid = [
  'ggggggggggggg..',
  'gPPPPPPPPPPPgjj',
  'gPPPPPPPPPPPgjj',
  'gCCCCCCCCCCCcjj',
  'gCCCCCCCCCCCcjj',
  'gCCCCCCCCCCCcjj',
  'g11111111111cjj',
  'gCCCCCCCCCCCcjj',
  'g11111111111cjj',
  'gCCCCCCCCCCCcjj',
  'gCCCCCCCCCCCcjj',
  'gCCCCCCCCCCCcjj',
  'gCCCCCCCCCCCcjj',
  'jjjjjjjjjjjjjjj',
];

/** 달력 날짜에 친 빨간 동그라미: 한 자리 (13×15) · 두 자리 (19×15) */
export const CIRCLE_1: Grid = [
  '....22222....',
  '..22.....22..',
  '.2.........2.',
  '.2.........2.',
  '2...........2',
  '2...........2',
  '2...........2',
  '2...........2',
  '2...........2',
  '2...........2',
  '2...........2',
  '.2.........2.',
  '.2.........2.',
  '..22.....22..',
  '....22222....',
];
export const CIRCLE_2: Grid = [
  '.....222222222.....',
  '...22.........22...',
  '.22.............22.',
  '.2...............2.',
  '2.................2',
  '2.................2',
  '2.................2',
  '2.................2',
  '2.................2',
  '2.................2',
  '2.................2',
  '.2...............2.',
  '.22.............22.',
  '...22.........22...',
  '.....222222222.....',
];

// ───────────────────────── 연필꽂이 (48×118) ─────────────────────────

/** 연필 끝 (5×8): 흑연 · 깎은 나무 · 칠한 몸 시작 (몸 색 g C c j 는 연필마다 바꿔 칠한다) · 몸 한 줄 (되풀이) */
export const PCIL_TIP: Grid = [
  '..X..',
  '..X..',
  '.uXw.',
  '.uWw.',
  '.uWw.',
  'uWWWw',
  'uWWWw',
  'gCCcj',
];
export const PCIL_BODY: Grid = ['gCCcj'];
/** 깡통 컵 (38×43): 앞 테 · 원기둥 명암(왼쪽 밝음 · 오른쪽 그늘) · 크림 상표 띠와 빨간 줄 둘 · 아래 테 */
export const CUP_TIN: Grid = [
  'iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm',
  'mmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmmz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'oOOOPPPPPPPPPPPPPPPPPPPPPppppppppyyyy',
  'oOOOPPPPPPPPPPPPPPPPPPPPPppppppppyyyy',
  'oOOOPPPPPPPPPPPPPPPPPPPPPppppppppyyyy',
  '1111222222222222222222222333333333333',
  '1111222222222222222222222333333333333',
  'oOOOPPPPPPPPPPPPPPPPPPPPPppppppppyyyy',
  'oOOOPPPPPPPPPPPPPPPPPPPPPppppppppyyyy',
  'oOOOPPPPPPPPPPPPPPPPPPPPPppppppppyyyy',
  'oOOOPPPPPPPPPPPPPPPPPPPPPppppppppyyyy',
  '1111222222222222222222222333333333333',
  '1111222222222222222222222333333333333',
  'oOOOPPPPPPPPPPPPPPPPPPPPPppppppppyyyy',
  'oOOOPPPPPPPPPPPPPPPPPPPPPppppppppyyyy',
  'oOOOPPPPPPPPPPPPPPPPPPPPPppppppppyyyy',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIIIIIIIIIIIIIIIIIIIIIImmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  'iIIIMMMMMMMMMMMMMMMMMMMMMmmmmmmmmzzzz',
  '.zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz.',
];
/** 컵 뒤로 꽂힌 빨간 가위 손잡이 (7×5) · 테두리에 걸친 보라 털실 자투리 (5×18) */
export const SCISSORS: Grid = [
  '.KKKK..',
  'KKkkKK.',
  'Kk..kK.',
  'KKkkKK.',
  '.KKKK..',
];
export const CUP_YARN: Grid = [
  '.TTT.',
  'TVVVT',
  'TV.VV',
  '.VV..',
  '..V..',
  '..V..',
  '.V...',
  '.V...',
  '..V..',
  '..V..',
  '...V.',
  '...V.',
  '..V..',
  '..V..',
  '.V...',
  '.V...',
  '..V..',
  '..V..',
];

// ───────────────────────── 스탠드 받침 (72×132) ─────────────────────────

/**
 * 둥근 북 받침 (67×67): 0~44 줄 윗면 타원 (왼쪽 위 밝은 테 i · 오른쪽 위 그늘 테 m · 가까운 쪽 밝은 테) ·
 * 아래로 22 줄 둥근 앞면 (왼쪽 M 밝음 · 오른쪽 m · 끝 z) · 바닥 그늘. 줄마다 손으로 정한 반폭 표대로 찍었다.
 * 가운데 12~33 열을 되풀이해 넓힌다.
 */
export const DRUM: Grid = [
  '..........................iiiiiiiiiiiiiii..........................',
  '.....................iiiiiiiiiiiiiiiiiiiiiiiii.....................',
  '..................iiiiiiiiiiiiiiiiiiiiiiiiiiiiiii..................',
  '...............iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm...............',
  '.............iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm.............',
  '...........iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm...........',
  '.........iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm.........',
  '........iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm........',
  '.......iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm.......',
  '......iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm......',
  '.....iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm.....',
  '....iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm....',
  '...iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm...',
  '..iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm..',
  '..iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm..',
  '.iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm.',
  '.iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm.',
  'iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm',
  'iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm',
  'iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm',
  'iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm',
  'iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm',
  'iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIm',
  'iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIi',
  'iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIi',
  'iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIi',
  'iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIi',
  'iIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIi',
  'MiIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIiz',
  'MiIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIiz',
  'MMiIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIizz',
  'MMiIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIizz',
  'MMMiIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIizzz',
  'MMMMiIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIizzzz',
  'MMMMmiIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIizzzzz',
  'MMMMmMiIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIimzzzzz',
  'MMMMmMMiIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIimmzzzzz',
  'MMMMmMMMiIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIimmmzzzzz',
  'MMMMmMMMMiIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIizmmmzzzzz',
  'MMMMmMMMMMMiIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIimmzmmmzzzzz',
  'MMMMmMMMMMMMMiIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIimmmmzmmmzzzzz',
  'MMMMmMMMMMMMMmMiIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIIimmmmmmzmmmzzzzz',
  'MMMMmMMMMMMMMmMMMMiIIIIIIIIIIIIIIIIIIIIIIIIIIIIIizmmmmmmmmzmmmzzzzz',
  'MMMMmMMMMMMMMmMMMMMMMiIIIIIIIIIIIIIIIIIIIIIIIimmmzmmmmmmmmzmmmzzzzz',
  'MMMMmMMMMMMMMmMMMMMMMMmMmmiIIIIIIIIIIIIIimmmmmmmmzmmmmmmmmzmmmzzzzz',
  'MMMMmMMMMMMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmmzmmmzzzzz',
  'MMMMmMMMMMMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmmzmmmzzzzz',
  'MMMMmMMMMMMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmmzmmmzzzzz',
  'MMMMmMMMMMMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmmzmmmzzzzz',
  'MMMMmMMMMMMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmmzmmmzzzzz',
  '.MMMmMMMMMMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmmzmmmzzzz.',
  '.MMMmMMMMMMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmmzmmmzzzz.',
  '..MMmMMMMMMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmmzmmmzzz..',
  '..MMmMMMMMMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmmzmmmzzz..',
  '...MmMMMMMMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmmzmmmzz...',
  '....mMMMMMMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmmzmmmz....',
  '.....MMMMMMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmmzmmm.....',
  '......MMMMMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmmzmm......',
  '.......MMMMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmmzm.......',
  '........MMMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmmz........',
  '.........MMMMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmmmm.........',
  '...........MMmMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmmmm...........',
  '.............mMMMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmmmm.............',
  '...............MMMMMMMmMmmmmmmmzmmmmmmmmzmmmmmmmmzmm...............',
  '..................MMMMMMmmmmmmmmmmmmmmmmmmmmmmmmm..................',
  '.....................zzzzzzzzzzzzzzzzzzzzzzzzz.....................',
  '..........................zzzzzzzzzzzzzzz..........................',
];
/** 목 (5×1): 멀리 위쪽(어둡게) · 가까이 아래쪽 · 용수철 고리 한 쌍 (9×2) · 목 받침 (13×5) */
export const NECK_FAR: Grid = ['jcccj'];
export const NECK_NEAR: Grid = ['cgCCc'];
export const SPRING: Grid = ['IiiiiiiiM', '..cgCCc..'];
export const SOCKET: Grid = [
  '...mmmmmmm...',
  '.mmMMMMMMMmm.',
  'mMMIIIIIIIMMm',
  '.mmMMMMMMMmm.',
  '...zzzzzzz...',
];
/** 윗면 가운데 스위치 (꺼짐 1 · 켜짐 3 · 반짝 2 · 5) */
export const SWITCH: Grid = [
  '..zzzzzzzz..',
  '.z22111111z.',
  'z2111111111z',
  'z1111111111z',
  '.z11111111z.',
  '..zzzzzzzz..',
];
export const SWITCH_ON: Grid = [
  '..zzzzzzzz..',
  '.z55333333z.',
  'z5333333333z',
  'z3333333333z',
  '.z33333333z.',
  '..zzzzzzzz..',
];
/** 켜진 갓에서 내려와 윗면에 고인 빛 (30×13) */
export const LAMP_POOL: Grid = [
  '.........oooooooooooo.........',
  '.....oooooOOOOOOOOOOooooo.....',
  '...oooOOOOOOOOOOOOOOOOOOooo...',
  '..ooOOOOOOOOOOOOOOOOOOOOOOoo..',
  '.ooOOOOOOOOOOOOOOOOOOOOOOOOoo.',
  'ooOOOOOOOOOOOOOOOOOOOOOOOOOOoo',
  'ooOOOOOOOOOOOOOOOOOOOOOOOOOOoo',
  'ooOOOOOOOOOOOOOOOOOOOOOOOOOOoo',
  '.ooOOOOOOOOOOOOOOOOOOOOOOOOoo.',
  '..ooOOOOOOOOOOOOOOOOOOOOOOoo..',
  '...oooOOOOOOOOOOOOOOOOOOooo...',
  '.....oooooOOOOOOOOOOooooo.....',
  '.........oooooooooooo.........',
];

// ───────────────────────── 펼친 공책 ─────────────────────────

/**
 * 펼친 공책 본 (52×34): 빨간 표지 가장자리 · 크림 두 쪽(왼쪽 2~24 열 · 오른쪽 27~48 열) · 가운데 골(25~26 열) ·
 * 7 줄마다 파란 줄 · 분홍 여백 선 · 연필 글씨 · 아래 종이 두께. 쪽마다 가운데 열 · 6~26 줄을 되풀이해 늘인다.
 */
export const NOTEBOOK: Grid = [
  '....................................................',
  '....................................................',
  '....................................................',
  '.gCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcc.',
  '.CoPPPPPPPPPPPPPPPPPPPPPPpyPPPPPPPPPPPPPPPPPPPPPPpc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PPPPPPPPPPPPPPPPPPpc.',
  '.CoPPP2PXXPXXXPXPXXXXPPPpyPPPP2PXXXXPXXPXXXPPPPPPpc.',
  '.Co1112111111111111111111py1111211111111111111111pc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PPPPPPPPPPPPPPPPPPpc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PPPPPPPPPPPPPPPPPPpc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PPPPPPPPPPPPPPPPPPpc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PPPPPPPPPPPPPPPPPPpc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PXXPXXXXPXXPPPPPPPpc.',
  '.Co1112111111111111111111py1111211111111111111111pc.',
  '.CoPPP2PXXXPXXPXXXXPPPPPpyPPPP2PPPPPPPPPPPPPPPPPPpc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PPPPPPPPPPPPPPPPPPpc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PPPPPPPPPPPPPPPPPPpc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PPPPPPPPPPPPPPPPPPpc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PPPPPPPPPPPPPPPPPPpc.',
  '.CoPPP2PXXPXXXXXPXXPPPPPpyPPPP2PXXXPXXPXXXXPPPPPPpc.',
  '.Co1112111111111111111111py1111211111111111111111pc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PPPPPPPPPPPPPPPPPPpc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PPPPPPPPPPPPPPPPPPpc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PPPPPPPPPPPPPPPPPPpc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PPPPPPPPPPPPPPPPPPpc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PPPPPPPPPPPPPPPPPppc.',
  '.CoPPP2PPPPPPPPPPPPPPPPPpyPPPP2PPPPPPPPPPPPPPPPpppc.',
  '.CoPPPPPPPPPPPPPPPPPPPPPpyPPPPPPPPPPPPPPPPPPPPPpyyc.',
  '.CPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpc.',
  '.Cppppppppppppppppppppppppppppppppppppppppppppppppc.',
  '.CPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpc.',
  '.Cyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyc.',
  '.cccccccccccccccccccccccccccccccccccccccccccccccccc.',
  '....................................................',
];

// ───────────────────────── 지우개 ─────────────────────────

/** 큰 지우개 (48×34): 하얀 고무 윗면 · 파란 종이 띠 (크림 줄 둘) · 앞면 18~31 줄 · 옆면 44~46 열 */
export const ERASER: Grid = [
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '.oOOOOOOOOOOOOOOOGgggggggggggggggggggggggggc....',
  '.OOOOOOOOOOOOOOOOggggggggggggggggggggggggggcc...',
  '.OOOOOOOOOOOOOOOOggggggggggggggggggggggggggccc..',
  '.OOOOOOOOOOOOOOOOggggggggggggggggggggggggggccc..',
  '.OOOOOOOOOOOOOOOOggggggggggggggggggggggggggccc..',
  '.OOOOOOOOOOOOOOOOggggggggggggggggggggggggggccc..',
  '.OOOOOOOOOOOOOOOOggggggggggggggggggggggggggccc..',
  '.OOOOOOOOOOOOOOOOggggggggggggggggggggggggggccc..',
  '.OOOOOOOOOOOOOOOOggggggggggggggggggggggggggccc..',
  '.OOOOOOOOOOOOOOOOggggggggggggggggggggggggggccc..',
  '.OOOOOOOOOOOOOOOOggggggggggggggggggggggggggccc..',
  '.PPPPPPPPPPPPPPPPCCCCCCCCCCCCCCCCCCCCCCCCCCccc..',
  '.PPPPPPPPPPPPPPPPCCCCCCCCCCCCCCCCCCCCCCCCCCccc..',
  '.PPPPPPPPPPPPPPPPCCCCCCCCCCCCCCCCCCCCCCCCCCccc..',
  '.PPPPPPPPPPPPPPPP11111111111111111111111111ccc..',
  '.PPPPPPPPPPPPPPPPCCCCCCCCCCCCCCCCCCCCCCCCCCccc..',
  '.PPPPPPPPPPPPPPPPCCCCCCCCCCCCCCCCCCCCCCCCCCccc..',
  '.PPPPPPPPPPPPPPPPCCCCCCCCCCCCCCCCCCCCCCCCCCccc..',
  '.PPPPPPPPPPPPPPPPCCCCCCCCCCCCCCCCCCCCCCCCCCccc..',
  '.PPPPPPPPPPPPPPPPCCCCCCCCCCCCCCCCCCCCCCCCCCccc..',
  '.PPPPPPPPPPPPPPPPCCCCCCCCCCCCCCCCCCCCCCCCCCccc..',
  '.PPPPPPPPPPPPPPPP11111111111111111111111111ccc..',
  '.PPPPPPPPPPPPPPPPCCCCCCCCCCCCCCCCCCCCCCCCCCccc..',
  '.PPPPPPPPPPPPPPPPCCCCCCCCCCCCCCCCCCCCCCCCCCccc..',
  '.PPPPPPPPPPPPPPPPCCCCCCCCCCCCCCCCCCCCCCCCCCccc..',
  '.PPPPPPPPPPPPPPPPCCCCCCCCCCCCCCCCCCCCCCCCCCccc..',
  '.ppppppppppppppppccccccccccccccccccccccccccjjj..',
  '................................................',
];
/** 작은 지우개 (48×28): 앞면 18~25 줄 · 옆면 33~34 열 */
export const ERASER_SMALL: Grid = [
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '.............oOOOOOOOGgggggggggggc..............',
  '.............OOOOOOOOggggggggggggcc.............',
  '.............OOOOOOOOggggggggggggcc.............',
  '.............OOOOOOOOggggggggggggcc.............',
  '.............OOOOOOOOggggggggggggcc.............',
  '.............OOOOOOOOggggggggggggcc.............',
  '.............OOOOOOOOggggggggggggcc.............',
  '.............PPPPPPPPCCCCCCCCCCCCcc.............',
  '.............PPPPPPPPCCCCCCCCCCCCcc.............',
  '.............PPPPPPPP111111111111cc.............',
  '.............PPPPPPPPCCCCCCCCCCCCcc.............',
  '.............PPPPPPPPCCCCCCCCCCCCcc.............',
  '.............PPPPPPPP111111111111cc.............',
  '.............PPPPPPPPCCCCCCCCCCCCcc.............',
  '.............PPPPPPPPCCCCCCCCCCCCcc.............',
  '.............ppppppppccccccccccccjj.............',
  '................................................',
];
/** 지우개 가루 더미 셋 · 돌돌 말린 부스러기 (48×24) */
export const ERASER_DUST: Grid = [
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '.......................oOOo.....................',
  '.....................oOOOPPo....................',
  '..........oOo.......oOOPPPPPp...................',
  '........oOOPPo....oOOPPPPPPPpp..................',
  '.......oOPPPPPp..oOPPPPPPPPPPPp.................',
  '......oOPPPPPPPpoPPPPPPPPPPPPPPp...oOo..........',
  '.....oPPPPPPPPPPPPPPPPPPPPPPPPPPpp.oOPPPo.......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPppoPPPPPPp.....',
  '...pppppppppppppppppppppppppppppppppppppppppp...',
  '..1..1....1...1.....1....1...1.....1..1....1....',
  '................................................',
];

// ───────────────────────── 자 · 연필 ─────────────────────────

/** 자: 왼쪽 끝 (4×24) · 눈금 30 칸 무늬 (긴 눈금 0 · 중간 15 · 짧은 눈금 3 칸마다) · 오른쪽 끝 (6×24). 숫자는 글씨로 얹는다 */
export const RULER_L: Grid = [
  '....', '....', '....', '....', '....', '....',
  '.gGG', '.gCC', '.gCC', '.gCC', '.gCC', '.gCC', '.gCC', '.gCC', '.gCC', '.gCC', '.gCC', '.gCC', '.gCC',
  '.ccc', '.ccc', '.jjj', '....', '....',
];
export const RULER_T: Grid = [
  '..............................',
  '..............................',
  '..............................',
  '..............................',
  '..............................',
  '..............................',
  'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
  'XCCXCCXCCXCCXCCXCCXCCXCCXCCXCC',
  'XCCXCCXCCXCCXCCXCCXCCXCCXCCXCC',
  'XCCCCCCCCCCCCCCXCCCCCCCCCCCCCC',
  'XCCCCCCCCCCCCCCXCCCCCCCCCCCCCC',
  'XCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'XCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CgggggggCCCCCCCCCCCCgggggggCCC',
  'cccccccccccccccccccccccccccccc',
  'cccccccccccccccccccccccccccccc',
  'jjjjjjjjjjjjjjjjjjjjjjjjjjjjjj',
  '..............................',
  '..............................',
];
export const RULER_R: Grid = [
  '......', '......', '......', '......', '......', '......',
  'GGGc..', 'CCCcc.', 'CCCcc.', 'CCCcc.', 'CCCcc.', 'CCCcc.', 'CCCcc.', 'CCCcc.', 'CCCcc.', 'CCCcc.', 'CCCcc.', 'CCCcc.', 'CCCcc.',
  'cccjj.', 'cccjj.', 'jjjjj.', '......', '......',
];

/** 누운 육각 연필: 깎은 끝 (12×11) · 몸 한 열 (되풀이, 윗면 밝음 · 가운데 · 아래 그늘) · 쇠 고리와 지우개 (16×11) */
export const PENCIL_TIP: Grid = [
  '........uuuu',
  '......uuWWWW',
  '.....uWWWWWW',
  '...XXWWWWWWW',
  '..XXXWWwWWWW',
  '.XXXXWWWWwWW',
  '..XXXWWwWWWW',
  '...XXWWWWWWw',
  '.....wwWWWww',
  '......wwwwww',
  '........vvvv',
];
export const PENCIL_BODY: Grid = ['G', 'g', 'g', 'C', 'C', 'C', 'C', 'C', 'c', 'c', 'j'];
export const PENCIL_END: Grid = [
  'IiIiIihhhhhhh...',
  'MmMmMmhAAAAAAa..',
  'MmMmMmAAAAAAAa..',
  'MmMmMmAAAAAAAa..',
  'MmMmMmAAAAAAAa..',
  'MmMmMmAAAAAAAa..',
  'MmMmMmAAAAAAAa..',
  'MmMmMmAAAAAAAa..',
  'mzmzmzaAAAAAAs..',
  'mzmzmzaaaaaaas..',
  'zzzzzzsssssss...',
];
/** 금박 글씨 흉내 (28×1) */
export const PENCIL_BRAND: Grid = ['1.1.1.1.1.1.1..1.1.1.1.1.1.1'];

// ───────────────────────── 종이띠 다발 · 종이별 병 ─────────────────────────

/** 종이띠 한 장 (46×4): 밝은 윗줄 · 바탕 둘 · 그늘. 색은 띠마다 바꿔 칠한다 */
export const STRIP: Grid = [
  '.ggggggggggggggggggggggggggggggggggggggggggggg',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'ccccccccccccccccccccccccccccccccccccccccccccc.',
];
/** 고무줄로 따로 묶은 노란 띠 다발 (18×16) · 빨간 고무줄 */
export const STRIP_BUNDLE: Grid = [
  '.44444444444444444',
  '555555555555555555',
  '555555555555555555',
  '66666666666666666.',
  '444444444444444444',
  '555555555555555555',
  '555555555555555555',
  '.66666666666666666',
  '.44444444444444444',
  '555555555555555555',
  '555555555555555555',
  '66666666666666666.',
  '444444444444444444',
  '555555555555555555',
  '555555555555555555',
  '777777777777777777',
];
export const STRIP_BAND: Grid = [
  '.12.',
  '1221',
  '.12.',
  '.12.',
  '.12.',
  '.12.',
  '.12.',
  '.12.',
  '.12.',
  '.12.',
  '.12.',
  '.12.',
  '.12.',
  '.12.',
  '.12.',
  '.22.',
];

/** 코르크 마개 (14×11) */
export const JAR_CORK: Grid = [
  '.uuuuuuuuuuuw.',
  'uWWWWWWWWWWWWw',
  'uWWwWWWWWWWWWw',
  'uWWWWWWWWwWWWw',
  'uWWWWWWWWWWWWw',
  'uWWWWWwWWWWWWw',
  'uWWWWWWWWWWWWw',
  'uWWwWWWWWWWWWw',
  'wwwwwwwwwwwwwv',
  'vvvvvvvvvvvvvv',
  '..............',
];
/**
 * 유리병 본 (30×20): 목 · 어깨(0~4 줄) · 몸통(5~16 줄, 7~12 줄 되풀이) · 두꺼운 바닥. 가운데 12~17 열을 되풀이해 넓힌다.
 * 속('.')은 비워 두어 먼저 깐 종이별이 비친다. 왼쪽 반사 줄 (o · O) · 오른쪽 그늘 (m · z).
 */
export const JAR_GLASS: Grid = [
  '.......iIIIIIIIIIIIIIIm.......',
  '.......iI............Im.......',
  '....iiiI..............Immm....',
  '..iiI....................Imm..',
  '.iI.......................mzz.',
  '.iIo...O..................mzz.',
  '.iIo...O..................mzz.',
  '.iIo......................mzz.',
  '.iIo......................mzz.',
  '.iIo......................mzz.',
  '.iIo......................mzz.',
  '.iIo......................mzz.',
  '.iIo......................mzz.',
  '.iIo......................mzz.',
  '.iIo......................mzz.',
  '.iIo......................mzz.',
  '.iIo......................mzz.',
  '.iIIIIIIIIIIIIIIIIIIIIIIIImzz.',
  '.mmmmmmmmmmmmmmmmmmmmmmmmmzzz.',
  '..zzzzzzzzzzzzzzzzzzzzzzzzzz..',
];
/**
 * 빽빽한 종이별 무늬 (15×10, 이어 깐다): 별 여섯 색 (노랑 g G c · 분홍 h A a · 하늘 l B b · 연두 4 5 6 · 보라 S R r · 주황 E D d),
 * 사이는 병 안쪽 그늘 (m).
 */
export const STAR_FILL: Grid = [
  'mmgmmmmhmmmmlmm',
  'mgGGmmhAAmmlBBm',
  'GGGGcAAAAaBBBBb',
  'mGccmmAaammBbbm',
  'mcmcmmamammbmbm',
  'EmmmmmmmmmSmmmm',
  'EEmm445mmSSRmmE',
  'EED44556SSRRrEE',
  'DDmm566mmRRrmmD',
  'mdmm6m6mmrmrmmd',
];
/** 병 위쪽 빈 유리 안 (1×1, 이어 깐다) */
export const GLASS_IN: Grid = ['M'];
/** 가운데 금색 별 「100」 (13×12, 글씨는 얹는다) · 맨 밑 삐뚤어진 첫 별 (7×6) */
export const GOLD_STAR: Grid = [
  '......1......',
  '.....111.....',
  '.....111.....',
  '1111111111111',
  '.11111111111.',
  '..111111111..',
  '...1111111...',
  '...1111111...',
  '..111...111..',
  '..11.....11..',
  '.11.......11.',
  '.............',
];
export const FIRST_STAR: Grid = [
  '..hh...',
  '.hAAh..',
  'AAAAAAa',
  '.aAAAa.',
  '..a..a.',
  '.......',
];
/** 유리를 지난 빛이 책상에 그린 무지개 (10×4) · 반짝임 (glow) */
export const RAINBOW: Grid = [
  'HHLLNNYYZZ',
  '.HHLLNNYYZ',
  '..HHLLNNYY',
  '...HHLLNN.',
];
export const JAR_GLOW: Grid = [
  '..........3..........',
  '.....................',
  '...3.................',
  '..............3......',
  '.....................',
  '.........3...........',
  '.....................',
  '.................3...',
  '.....3...............',
  '.....................',
  '...........3.........',
];

// ───────────────────────── 휴대폰 (72×120) ─────────────────────────

/**
 * 휴대폰 본 (26×25): 둥근 모서리 몸 · 스피커 · 카메라 · 검은 호수 같은 화면 · 앞쪽 두께(충전 단자) · 오른쪽 옆면.
 * 6~17 열 · 6~17 줄을 되풀이해 늘인다.
 */
export const PHONE: Grid = [
  '..ggggggggggggggggggg.....',
  '.gCCCC7777CCC8CCCCCCCc....',
  '.gCCCCCCCCCCCCCCCCCCCc9...',
  '.gCIIIIIIIIIIIIIIIIICc99..',
  '.gCIIIIIIIIIIIIIIIIICc999.',
  '.gCIIIIIIIIIIIIIIIIICc999.',
  '.gCIIIIIIIIIIIIIIIIICc999.',
  '.gCIIIIIIIIIIIIIIIIICc999.',
  '.gCIIIIIIIIIIIIIIIIICc999.',
  '.gCIIIIIIIIIIIIIIIIICc999.',
  '.gCIIIIIIIIIIIIIIIIICc999.',
  '.gCIIIIIIIIIIIIIIIIICc999.',
  '.gCIIIIIIIIIIIIIIIIICc999.',
  '.gCIIIIIIIIIIIIIIIIICc999.',
  '.gCIIIIIIIIIIIIIIIIICc999.',
  '.gCIIIIIIIIIIIIIIIIICc999.',
  '.gCIIIIIIIIIIIIIIIIICc999.',
  '.gCIIIIIIIIIIIIIIIIICc999.',
  '.gCIIIIIIIIIIIIIIIIICc999.',
  '.gCCCCCCCCCCCCCCCCCCCc999.',
  '..cccccccccccccccccccc999.',
  '..hhhhhhhhhhhhhhhhhhhh999.',
  '..AAAAAAAAOOOAAAAAAAAA999.',
  '..aaaaaaaaaaaaaaaaaaaa99..',
  '..........................',
];
/** 화면에 비친 달빛 줄 (14×14) · 충전 표시 (11×5, 숨쉬기: dim 은 5) · 케이블 (6×8) */
export const PHONE_SHINE: Grid = [
  '.............1',
  '............12',
  '...........12.',
  '..........12..',
  '.........12...',
  '........12....',
  '.......12.....',
  '......12......',
  '.....12.......',
  '....12........',
  '...12.........',
  '..12..........',
  '.12...........',
  '12............',
];
export const BATTERY: Grid = [
  '666666666..',
  '644444446..',
  '64444444666',
  '644444446..',
  '666666666..',
];
export const BATTERY_DIM: Grid = [
  '666666666..',
  '655555556..',
  '65555555666',
  '655555556..',
  '666666666..',
];
export const CABLE: Grid = [
  '..OO..',
  '..Oo..',
  '.Oo...',
  '.Oo...',
  '..Oo..',
  '...Oo.',
  '...Oo.',
  '..Oo..',
];

// ───────────────────────── 탁상 달력 · 시험지 ─────────────────────────

/** 탁상 달력 (72×64): 용수철 고리 · 초록 머리 · 크림 장 · 뒷받침 · 바닥 그늘. 날짜 · 동그라미 · 날짜 칸은 얹는다 */
export const CALENDAR: Grid = [
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '.......iI..iI..iI..iI..iI..iI..iI..iI..iI..iI..iI..iI..iI..iI...........',
  '.......IM..IM..IM..IM..IM..IM..IM..IM..IM..IM..IM..IM..IM..IM...........',
  '.......IM..IM..IM..IM..IM..IM..IM..IM..IM..IM..IM..IM..IM..IM..W........',
  '.......IM..IM..IM..IM..IM..IM..IM..IM..IM..IM..IM..IM..IM..IM..WW.......',
  '.......Mm..Mm..Mm..Mm..Mm..Mm..Mm..Mm..Mm..Mm..Mm..Mm..Mm..Mm..uWw......',
  '....GggggggggggggggggggggggggggggggggggggggggggggggggggggggcuWw.........',
  '....gCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcuWw.........',
  '....gCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcuWw.........',
  '....gCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcuWw.........',
  '....gCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcuWw.........',
  '....gCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcuWw.........',
  '....gCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcuWw.........',
  '....ccccccccccccccccccccccccccccccccccccccccccccccccccccccccuWw.........',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwv........',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwv........',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwv........',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwv........',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwv........',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwv........',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwv........',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwv........',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwv........',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwv........',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwv........',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwv........',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwv........',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvv.......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvv.......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvv.......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvv.......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvv.......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvv.......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvv.......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvv.......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvv.......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvv.......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvv.......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvv......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvv......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvv......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvv......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvv......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvv......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvv......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvv......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvv......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvv......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvv......',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvvv.....',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvvv.....',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvvv.....',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvvv.....',
  '....oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpuWwvvvv.....',
  '....ppppppppppppppppppppppppppppppppppppppppppppppppppppppppuWwvvvv.....',
  '....yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyuWwvvvv.....',
  '....yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyuWwvvvv.....',
  '....vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv....',
  '........................................................................',
];

/** 시험지 더미 (72×54): 맨 위 장(윗면 17~42 줄: 문제 줄 · 빨간 채점 · 점수 밑줄) · 쌓인 종이 앞면(43~50 줄) · 옆면 */
export const TEST_PAPERS: Grid = [
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '........................................................................',
  '....pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppp........',
  '...OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOp........',
  '...OPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPPPP2PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPPP2P2PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPP11111111111111111111111111111111111111111111PPPPPPPPPPp........',
  '...OPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPPPP2PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPPP2P2PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPP11111111111111111111111111111111111111222222222222PPPPp........',
  '...OPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPP222222222222PPPPp........',
  '...OPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPPPP2PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPPP2P2PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPP11111111111111111111111111111111111111111111PPPPPPPPPPp........',
  '...OPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPPP22PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPP2PP2PPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPP1121111111111111111111111111111111111111111PPPPPPPPPPPp........',
  '...OPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPp........',
  '...OPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpy.......',
  '...pppppppppppppppppppppppppppppppppppppppppppppppppppppppppppppyy......',
  '...3333333333333333333333333333333333333333333333333333333333333yyy.....',
  '...4444444444444444444444444444444444444444444444444444444444444yyy.....',
  '...3333333333333333333333333333333333333333333333333333333333333yyy.....',
  '...4444444444444444444444444444444444444444444444444444444444444yyy.....',
  '...3333333333333333333333333333333333333333333333333333333333333yyy.....',
  '...4444444444444444444444444444444444444444444444444444444444444yyy.....',
  '...3333333333333333333333333333333333333333333333333333333333333yyy.....',
  '...3333333333333333333333333333333333333333333333333333333333333yyy.....',
  '...yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy.....',
  '........................................................................',
  '........................................................................',
];

// ───────────────────────── 사탕 깡통 · 테이프 커터 · 머리끈 ─────────────────────────

/** 둥근 사탕 깡통 (48×52): 뚜껑 윗면 · 뚜껑 띠 · 원기둥 몸 · 사탕 그림 크림 띠 · 아래 테 */
export const CANDY_TIN: Grid = [
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '......GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG.......',
  '...ggGGGGGgggggggggggggggggggggggggggggggggg....',
  '..ggggggggggggggggggggggggggggggggggggggggggg...',
  '..gCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcccccjj...',
  '..gCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcccccjj...',
  '..gCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcccccjj...',
  '..ccccccccccccccccccccccccccccccccccccccccccc...',
  '...gggCCCCCCCCCCCCCCCCCCCCCCCCCCCCccccccjjjj....',
  '...gggCCCCCCCCCCCCCCCCCCCCCCCCCCCCccccccjjjj....',
  '...gggCCCCCCCCCCCCCCCCCCCCCCCCCCCCccccccjjjj....',
  '...gggCCCCCCCCCCCCCCCCCCCCCCCCCCCCccccccjjjj....',
  '...oooPPPPPPPPPPPPPPPPPPPPPPPPPPPPppppppyyyy....',
  '...oooPPPPPPPPPPPPPPPPPPPPPPPPPPPPppppppyyyy....',
  '...oooPPPPPPPPPPPPPPPPPPPPPPPPPPPPppppppyyyy....',
  '...oooPPPPPPPPPPPPPPPPPPPPPPPPPPPPppppppyyyy....',
  '...oooPPPPPPPPPPPPPPPPPPPPPPPPPPPPppppppyyyy....',
  '...oooPPPPPPPPPPPPPPPPPPPPPPPPPPPPppppppyyyy....',
  '...oooPPPPPPPPPPPPPPPPPPPPPPPPPPPPppppppyyyy....',
  '...oooPPPPPPPPPPPPPPPPPPPPPPPPPPPPppppppyyyy....',
  '...oooPPPPPPPPPPPPPPPPPPPPPPPPPPPPppppppyyyy....',
  '...gggCCCCCCCCCCCCCCCCCCCCCCCCCCCCccccccjjjj....',
  '...gggCCCCCCCCCCCCCCCCCCCCCCCCCCCCccccccjjjj....',
  '...gggCCCCCCCCCCCCCCCCCCCCCCCCCCCCccccccjjjj....',
  '...gggCCCCCCCCCCCCCCCCCCCCCCCCCCCCccccccjjjj....',
  '...gggCCCCCCCCCCCCCCCCCCCCCCCCCCCCccccccjjjj....',
  '...gggCCCCCCCCCCCCCCCCCCCCCCCCCCCCccccccjjjj....',
  '...gggCCCCCCCCCCCCCCCCCCCCCCCCCCCCccccccjjjj....',
  '...gggCCCCCCCCCCCCCCCCCCCCCCCCCCCCccccccjjjj....',
  '...ccccccccccccccccccccccccccccccccccccccccc....',
  '....jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj.....',
  '................................................',
  '................................................',
];
/** 깡통 띠에 그린 사탕 여섯 (41×3, 깡통 (3, 34)) */
export const TIN_CANDIES: Grid = [
  '...1......2......3......1......2......3..',
  '..111....222....333....111....222....333.',
  '...1......2......3......1......2......3..',
];

/** 투명 테이프 롤 (20×17): 호박색 고리 · 종이 심 · 가운데 구멍 */
export const TAPE_ROLL: Grid = [
  '......eeeeeeee......',
  '....eeTTTTTTTTtt....',
  '...eTTTTTTTTTTTTt...',
  '..eTTTTTTTTTTTTTTt..',
  '.eTTTTTuuuuuuTTTTTt.',
  '.eTTTTuWWWWWWuTTTTt.',
  'eTTTTuWWXXXXWWuTTTTt',
  'eTTTTuWXXXXXXWuTTTTt',
  'eTTTTuWXXXXXXWuTTTTt',
  'eTTTTuWXXXXXXWuTTTtt',
  'eTTTTuWWXXXXWWuTTTtt',
  '.eTTTTuWWWWWWuTTTtt.',
  '.eTTTTTuuuuuuTTTTtt.',
  '..tTTTTTTTTTTTTTtt..',
  '...tTTTTTTTTTTTtt...',
  '....ttTTTTTTTTtt....',
  '......tttttttt......',
];
/** 테이프 커터 몸 (48×34): 밝은 윗면(18~22 줄) · 앞면(23~31 줄, 밝은 홈 줄) · 옆면(43~45 열) */
export const TAPE_CUTTER: Grid = [
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '................................................',
  '.ggggggggggggggggggggggggggggggggggggggggggc....',
  '.Gggggggggggggggggggggggggggggggggggggggggggcc..',
  '.ggggggggggggggggggggggggggggggggggggggggggccc..',
  '.ggggggggggggggggggggggggggggggggggggggggggccc..',
  '.ggggggggggggggggggggggggggggggggggggggggggccc..',
  '.CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcccc..',
  '.CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcccc..',
  '.CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcccc..',
  '.CggggggggggggggggggggggggggggggggggggggCCcccc..',
  '.CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcccc..',
  '.CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcccc..',
  '.CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcccc..',
  '.CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcccc..',
  '.CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCcccc..',
  '.jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj..',
  '................................................',
];
/** 톱니 칼날 (8×3) */
export const BLADE: Grid = [
  'i.i.i.i.',
  'IIIIIIIm',
  'MMMMMMMz',
];

/** 분홍 머리끈 고리 (16×9) · 노란 방울 (5×4) */
export const HAIR_LOOP: Grid = [
  '....gggggggg....',
  '..ggCCCCCCCCcc..',
  '.gCC........cCc.',
  'gCc..........cCc',
  'gC............Cc',
  'cC............Cj',
  '.cCc........cCj.',
  '..ccCCCCCCCCcj..',
  '....jjjjjjjj....',
];
export const HAIR_BEAD: Grid = [
  '.hAa.',
  'hAAAa',
  'AAAas',
  '.aas.',
];

// ───────────────────────── 우유팩 (48×92) ─────────────────────────

/**
 * 우유팩: 굽은 분홍 빨대 · 접힌 꼭대기 · 박공 지붕(17~32 줄) · 흰 앞면(33~89 줄, 물결진 파란 띠 · 초록 밑) · 오른쪽 옆면(38~43 열).
 * 「우유」 글씨는 얹는다.
 */
export const MILK: Grid = [
  '........................3222222.................',
  '........................2333332.................',
  '........................2222222.................',
  '........................222.....................',
  '........................232.....................',
  '........................222.....................',
  '........................222.....................',
  '........................232.....................',
  '........................222.....................',
  '........................222.....................',
  '........................232.....................',
  '........................222.....................',
  '........................222.....................',
  '................oOOOOOO232Op....................',
  '................OPPPPPPPPPPp....................',
  '................OPPPPPPPPPPp....................',
  '................pppppppppppp....................',
  '.....................oO.........................',
  '....................oOOp........................',
  '...................oOOOOp.......................',
  '..................oOOOOOOp......................',
  '.................oOOOOOOOOp.....................',
  '................oOOOOOOOOOOp....................',
  '...............oOOOOOOOOOOOOp...................',
  '..............oOOOOOOOOOOOOOOp..................',
  '.............oOOOOOOOOOOOOOOOOp.................',
  '............oOOOOOOOOOOOOOOOOOOp................',
  '...........oOOOOOOOOOOOOOOOOOOOOpy..............',
  '..........oOOOOOOOOOOOOOOOOOOOOOOpyy............',
  '.........oOOOOOOOOOOOOOOOOOOOOOOOOpyyy..........',
  '........oOOOOOOOOOOOOOOOOOOOOOOOOOOpyyyy........',
  '.......oOOOOOOOOOOOOOOOOOOOOOOOOOOOOpyyyyy......',
  '......oOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOpyyyyy.....',
  '......pppppppppppppppppppppppppppppppyyyyyy.....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPPPPPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPPPPhhhPPPPPPPPPPPPPPPPPpyyyyyy....',
  '......oPPPPPPPhhhAAAhhhPPPPPPPPPhhhhPpyyyyyy....',
  '......oPPPPhhhAAAAAAAAAhhhPPPhhhAAAAhpaaaaaa....',
  '......hhhhhAAAAAAAAAAAAAAAhhhAAAAAAAAAsaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAasaaaaa....',
  '......aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaasaaaaa....',
  '......lBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbnbbbbb....',
  '......lBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbnbbbbb....',
  '......lBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbnbbbbb....',
  '......lBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbnbbbbb....',
  '......lBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbnbbbbb....',
  '......lBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbnbbbbb....',
  '......lBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbnbbbbb....',
  '......lBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbnbbbbb....',
  '......lBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBbnbbbbb....',
  '......bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbnnnnnn....',
  '......nnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnnn....',
  '................................................',
];

// ───────────────────────── 메모 벽 (96×48) ─────────────────────────

/** 시간표 종이 본 (8×6, 9-조각으로 53×38): 크림 종이 · 아래 그늘 */
export const TIMETABLE: Grid = [
  'oOOOOOOp',
  'OPPPPPPp',
  'OPPPPPPp',
  'OPPPPPPp',
  'OPPPPPPp',
  'pppppppy',
];
/** 시간표 한 칸 (8×8): 과목 색 C · 글씨 줄 c (칸마다 색을 바꿔 칠한다) */
export const SUBJECT: Grid = [
  'gCCCCCCC',
  'CCCCCCCC',
  'CcccccCC',
  'CCCCCCCC',
  'CcccCCCC',
  'CCCCCCCC',
  'CCCCCCCc',
  'cccccccc',
];
/** 귀퉁이 테이프 (7×4) */
export const MEMO_TAPE: Grid = [
  'eeeeeee',
  'TTTTTTT',
  'TTTTTTT',
  'ttttttt',
];
/** 노란 쪽지 (24×24): 빨간 압정 · 매직 글씨 · 접힌 귀퉁이 */
export const STICKY: Grid = [
  '..........lBb...........',
  'cccccccccccncccccccccccc',
  'cccccccccccccccccccccccc',
  'gCCCCCCCCCCCCCCCCCCCCCCc',
  'gCCCCCCCCCCCCCCCCCCCCCCc',
  'gCCXXXCXXXXCXXXXXCCCCCCc',
  'gCCCCCCCCCCCCCCCCCCCCCCc',
  'gCCCCCCCCCCCCCCCCCCCCCCc',
  'gCCXXXXCXXXCXXXXCCCCCCCc',
  'gCCCCCCCCCCCCCCCCCCCCCCc',
  'gCCCCCCCCCCCCCCCCCCCCCCc',
  'gCCXXCXXXXXCXXCCCCCCCCCc',
  'gCCCCCCCCCCCCCCCCCCCCCCc',
  'gCCCCCCCCCCCCCCCCCCCCCCc',
  'gCCXXXXXCXXXXCCCCCCCCCCc',
  'gCCCCCCCCCCCCCCCCCCCCCCc',
  'gCCCCCCCCCCCCCCCCCCCCCCc',
  'gCCCCCCCCCCCCCCCCCCCCCCc',
  'gCCCCCCCCCCCCCCCCCCCCCCc',
  'gCCCCCCCCCCCCCCCCCCCCCc.',
  'gCCCCCCCCCCCCCCCCCCCCj..',
  'gCCCCCCCCCCCCCCCCCCcj...',
  'gCCCCCCCCCCCCCCCCCcj....',
  'cccccccccccccccccjj.....',
];

// ───────────────────────── 책상 끝 · 숫자 발판 ─────────────────────────

/** 책상 끝 무늬 (32×24, 이어 깐다): 둥글게 깎은 밝은 윗면 · 모서리 반짝 · 앞판 · 아래로 떨어지는 어둠 (1~4) */
export const DESK_EDGE: Grid = [
  'gggggggggggggggggggggggggggggggg',
  'ggggCCCgggggggggggggggCCCCgggggg',
  'gggggggggggggCCCgggggggggggggggg',
  'gggCCgggggggggggggggggggggCCgggg',
  'gggggggggggggggggggCCCgggggggggg',
  'GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG',
  'CCCCCCCCCCCCCCCCCCCCCCCCCCCCCCCC',
  'cccccccccccccccccccccccccccccccc',
  'cccccccjjjcccccccccccccccccccccc',
  'cccccccccccccccccccccjjjjccccccc',
  'cccccccccccccccccccccccccccccccc',
  'ccjjjccccccccccccccccccccccccccc',
  'cccccccccccccccjjjcccccccccccccc',
  'cccccccccccccccccccccccccccjjjcc',
  'cccccccccccccccccccccccccccccccc',
  'ccccccccjjjjcccccccccccccccccccc',
  'cccccccccccccccccccccccccccccccc',
  'ccccccccccccccccccccjjjccccccccc',
  'cccccccccccccccccccccccccccccccc',
  'jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj',
  '11111111111111111111111111111111',
  '22222222222222222222222222222222',
  '33333333333333333333333333333333',
  '44444444444444444444444444444444',
];

/** 숫자 발판 (24×24): 밝은 윗면 0~16 줄 · 두꺼운 앞면 17~20 줄 · 옆면. 숫자는 얹는다 */
export const NUMPAD: Grid = [
  '...oooooooooooooooo.....',
  '..oPPPPPPPPPPPPPPPPo....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..pppppppppppppppppp....',
  '..ppppppppppppppppppzz..',
  '..ppppppppppppppppppzz..',
  '..ppppppppppppppppppzz..',
  '..yyyyyyyyyyyyyyyyyyzz..',
  '........................',
  '........................',
  '........................',
];
/** 눌린 숫자 발판 (24×24): 3 줄 내려앉고 앞면이 한 줄 */
export const NUMPAD_ON: Grid = [
  '........................',
  '........................',
  '........................',
  '...oooooooooooooooo.....',
  '..oPPPPPPPPPPPPPPPPo....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..oPPPPPPPPPPPPPPPPp....',
  '..pppppppppppppppppp....',
  '..yyyyyyyyyyyyyyyyyyzz..',
  '........................',
  '........................',
  '........................',
];
