/**
 * 기억의 상징물 · 기억 조각 · 종이별 · 밀 덩어리 (keepsakes.ts) 의 손찍기 격자.
 * 글자 뜻은 px/items.ts 와 같다: G g C c j 주된 색 · . h A a s 둘째 색 · . l B b n 셋째 색 ·
 * O o P p y 종이 · . u W w v 나무 · I i M m z 쇠 · X 먹 · R 빨강 포인트 · 1~5 포인트 색.
 * 큰 그림은 조각 격자를 자리(x, y)에 겹쳐 놓는다 (keepsakes.ts 의 PARTS).
 */
import type { Grid } from './grid.ts';

// ───────────────────────── 상징물 (22×22 안) ─────────────────────────

/** 종이별 (20×18): 왼쪽 위 면이 밝고, 가운데 접힌 금 */
export const STAR_BIG: Grid = [
  '.........gG.........',
  '.........gC.........',
  '........gGCc........',
  '........gGCc........',
  '.......gGGCCc.......',
  'gggggggGGGCCCcccccc.',
  '.gGGGGGGGGCCCCCCCcc.',
  '..gGGGGGGGCCCCCCcc..',
  '...gGGGGGGCCCCCcc...',
  '....gGGGGGCCCCcc....',
  '.....CCCCCCCCcc.....',
  '.....CCCCCCCCcc.....',
  '....CCCCCcCCCCcc....',
  '....CCCCc..cCCcc....',
  '...CCCcc....ccCcc...',
  '...CCcc......cccc...',
  '..CCc..........ccc..',
  '..cc............cc..',
];

/** 작은 종이별 (15×11) */
export const STAR_MID: Grid = [
  '.......C.......',
  '......gCc......',
  '......GCc......',
  'ggggGGGCCcccccc',
  '.gGGGGGCCCCccc.',
  '..gGGGGCCCcc...',
  '...CCCCCCCc....',
  '...CCCCcCCcc...',
  '..CCCc...cCcc..',
  '..Ccc.....ccc..',
  '.cc.........cc.',
];
/** 접다 만 띠 (8×3) */
export const STRIP: Grid = [
  'GGGGGGGg',
  'CCCCCCCc',
  'cccccccj',
];

/** 리본 매듭 (9×5) */
export const BOW: Grid = [
  'Rr.....rR',
  'RRr...rRR',
  'RRRr1rRRR',
  'RRr1RRrRR',
  'Rr..r..rR',
];
/** 열쇠 고리 (11×9) · 막대 (10×6) */
export const KEY_RING: Grid = [
  '...ggGGc...',
  '.gGGcccGGc.',
  'gGGc...cGcc',
  'gGc.....cCc',
  'gCc.....cCc',
  'gCc.....cCc',
  'cCCc...cCcj',
  '.cCCcccCcj.',
  '...ccccjj..',
];
export const KEY_BIT: Grid = [
  'gGGGGGGGc.',
  'CCCCCCCCc.',
  'cccccccccj',
  '.Cc..CCc..',
  '.cc..Ccc..',
  '.....cj...',
];

/** 우산 (19×17): 둥근 덮개 · 살 · 굽은 손잡이 */
export const UMBRELLA: Grid = [
  '........gGc........',
  '....ggGGgCCCcc.....',
  '..gGGGgCCCCgCCcc...',
  '.gGGGgCCCCCgCCCcc..',
  'gGGGgCCCCCCgCCCCcc.',
  'gGGgCCCCCCCgCCCCCcj',
  'CCcCCcCCcCCcCCcCCcj',
  'cj.cj.cj.Wcj.cj.cj.',
  '.........W.........',
  '.........W.........',
  '.........W.........',
  '.........W.........',
  '.........W.........',
  '.........w.........',
  '.........w.........',
  '......w..w.........',
  '.......ww..........',
];

/** 바늘과 빨간 실 (18×16) */
export const NEEDLE: Grid = [
  '...............IM.',
  '..............Im.M',
  '.............IM.R.',
  '............IM...R',
  '...........IM....R',
  '..........IM.....R',
  '.........IM.....R.',
  '........IM.....R..',
  '.......IM.....R...',
  '......IM.....R....',
  '..CCC.M.....R.....',
  '.CGgCC....RR......',
  'CGCCCcCRRR........',
  'CCCCCcc...........',
  '.cCCccj...........',
  '..cccj............',
];

/** 옛 전화기 (18×14): 수화기 · 몸통 · 둥근 다이얼 */
export const PHONE: Grid = [
  '..oPPPPPPPPPPPPp..',
  '.oPPPPPPPPPPPPPPp.',
  'oPPp..........pPPp',
  'pPp............pPp',
  '..oPPPPPPPPPPPPp..',
  '.oPPPPPAAAAPPPPpp.',
  '.PPPPPAaAAaAPPPpp.',
  '.PPPPAAA..AaAPPpp.',
  '.PPPPAa....aAPPpp.',
  '.PPPPAA....AAPPpp.',
  '.PPPPPAaAAaAPPPpp.',
  '.PPPPPPAAAAPPPPpp.',
  '.ppppppppppppppyy.',
  '..yy..........yy..',
];

/** 초 (8×17): 불꽃 · 파란 초 · 촛농 */
export const CANDLE: Grid = [
  '...1....',
  '..121...',
  '..131...',
  '..111...',
  '...X....',
  '.gGGGCc.',
  '.gGCCCc.',
  '.gGCCCcc',
  '.gGCCCc.',
  '.gGCCCc.',
  '.gGCCCc.',
  '.gGCCCc.',
  '.gGCCCc.',
  '.gGCCCc.',
  '.gGCCCc.',
  'ccccccjj',
  '.jjjjjj.',
];

/** 사진 액자 (18×16): 할머니(H 흰머리 · C 보라 옷)와 하루(A 머리 · B 노란 옷) */
export const PHOTO: Grid = [
  'uuuuuuuuuuuuuuuuuw',
  'uWWWWWWWWWWWWWWWwv',
  'uWooooooooooooowwv',
  'uWoPPPPPPPPPPPPpwv',
  'uWoPPHHHPPPPPPPpwv',
  'uWoPHHHHHPPAAAPpwv',
  'uWoPSSSSPPAAAAAPwv',
  'uWoPSXSXPPASXSAPwv',
  'uWoPSSSSPPPSSSPpwv',
  'uWoPCCCCCPPBBBPpwv',
  'uWoCCCCCCCBBBBBpwv',
  'uWoCCCCCCCBBBBBpwv',
  'uWoCCCCCCCBBBBBpwv',
  'uWppppppppppppppwv',
  'uwwwwwwwwwwwwwwwwv',
  'wvvvvvvvvvvvvvvvvv',
];

/** 곰 손인형 (14×18) */
export const PUPPET: Grid = [
  '.EFf......EFf.',
  'EF2Ff....EF2Ff',
  'FF2FFFFFFF2Fff',
  '.FFFFFFFFFFFf.',
  'EFFFFFFFFFFFFf',
  'EFFXFFFFFFXFFf',
  'EFFFFAAAAFFFFf',
  'EF3FAAyyAAF3Ff',
  'FFFFFAAAAFFFff',
  '.fFFFFFFFFFff.',
  '..ffffffffff..',
  '.gGGGGGGGGGCc.',
  'gGGCCCCCCCCCcc',
  'gGCCCC44CCCCcc',
  'gGCCCCCCCCCCcc',
  'gGCCCCCCCCCCcc',
  'GCCCCCCCCCCCcc',
  'cccccccccccccj',
];

/** 종이별 병 (12×17) */
export const JAR: Grid = [
  '..uWWWWWWw..',
  '..WWWWWWWw..',
  '..wwwwwwwv..',
  '.gIIGGGGGGg.',
  'gIGGG1GGGGGg',
  'GIG3GGG2GG4g',
  'GIGG2GGGGGGg',
  'GI1GGG4GG3Gg',
  'GIGG5GG1GGGg',
  'GI3GGG2GG5Gg',
  'GIGG1GGG3GGg',
  'GI2G4G5GG1Gg',
  'GG5G13GG42Gg',
  'G413G2G5G13g',
  'G2541352441g',
  'G1352413523g',
  '.gggggggggg.',
];

/** 편지 봉투 (18×13): 접힌 덮개 · 빨간 봉인 */
export const LETTER: Grid = [
  'oPPPPPPPPPPPPPPPPp',
  'PpPPPPPPPPPPPPPPpp',
  'PPpPPPPPPPPPPPPpPp',
  'PPPpPPPPPPPPPPpPPp',
  'PPPPpPPPPPPPPpPPPp',
  'PPPPPpPPPPPPpPPPPp',
  'PPPPPPppRRppPPPPPp',
  'PPPPPPPR1RRRPPPPPp',
  'PPPPPPPRRRRRPPPPPp',
  'PPPPPPPPRRRPPPPPPp',
  'PPPPPPPPPPPPPPPPPp',
  'PPPPPPPPPPPPPPPPPp',
  'pppppppppppppppppy',
];

/** 둥근 빛 구슬 (14×14): 모르는 상징물 */
export const ORB: Grid = [
  '....gGGGGc....',
  '..gGGOOGGGCc..',
  '.gGGOOGGGCCCc.',
  '.gGOGGGCCCCCc.',
  'gGGGGGCCCCCCcc',
  'gGGGGCCCCCCCcc',
  'gGGGCCCCCCCCcc',
  'GGGCCCCCCCCccc',
  'GCCCCCCCCCCccj',
  'CCCCCCCCCCcccj',
  '.CCCCCCCCcccj.',
  '.cCCCCCcccccj.',
  '..cccccccjj...',
  '....ccjjjj....',
];

// ───────────────────────── 기억 조각 (16×16, 외곽선 없음) ─────────────────────────

/** 빛나는 구슬 (10×10): 바깥 하늘빛 · 안쪽 흰 빛 */
export const SHARD: Grid = [
  '...gGGc...',
  '.gGOOGCc..',
  '.GOOOOCCc.',
  'gOOOOOOCcc',
  'GOOOOOOCCc',
  'GOOOOOCCCc',
  'gGOOOCCCcc',
  '.GCCCCCCc.',
  '..cCCCcc..',
  '...cccc...',
];
/** 반짝이 (16×16): 0 · 2 는 십자, 1 · 3 은 엇갈림 */
export const SPARK_CROSS: Grid = [
  '........1.......',
  '........1.......',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '1..............1',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '........1.......',
];
export const SPARK_X: Grid = [
  '................',
  '................',
  '..1..........1..',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '................',
  '..1..........1..',
  '................',
  '................',
];

/** 바닥에 떨어진 종이별 (9×9) */
export const STAR_SMALL: Grid = [
  '....G....',
  '...gCc...',
  'gggGCCccc',
  '.gGGCCCc.',
  '..GCCCc..',
  '..CCcCc..',
  '.CCc.cCc.',
  '.cc...cc.',
  '.........',
];

// ───────────────────────── 밀 덩어리 (22×22, 그림 24×30 의 (1, 7)) ─────────────────────────

export const BLK_COOKIE: Grid = [
  '.......gGGGGc.........',
  '....ggGGGGGGGCcc......',
  '...gGGGGGGGGGGCCc.....',
  '..gGGGGGXxGGGGCCCc....',
  '.gGGGGGGGGGGGCCCCCc...',
  '.gGGGGGGGGGGGGCCCCcc..',
  'gGGGGXxGGGGGGCCCCCCcc.',
  'gGGGGGGGGGGGGGXxCCCCc.',
  'gGGGGGGGGGGGCCCCCCCCcc',
  'GGGGGGGGGGGCCCCCCCCCcc',
  'GGGGGGGGGCCCCCCCCCCCcc',
  'GGGGGGGGCCCCCCCCCCCCcc',
  'GGGGGGXxCCCCCCCCCCCccj',
  'CGGGGCCCCCCCCCCXxCCccj',
  'CCCCCCCCCCCCCCCCCCCccj',
  '.CCCCCCCCCCCCCCCCCccj.',
  '.CCCCCCCCCXxCCCCCcccj.',
  '..CCCCCCCCCCCCCCcccj..',
  '...cCCCCCCCCCCcccjj...',
  '....ccccccccccccjj....',
  '......ccccccjjjj......',
  '......................',
];
export const BLK_BOOK: Grid = [
  '......................',
  '......................',
  '......................',
  '......................',
  '......................',
  'gggggggggggggggggggggc',
  'gGGGGGGGGGGGGGGGGGGGcc',
  'gGGGGGGGGGGGGGGGGGGGcc',
  'CCCCCCCCCCCCCCCCCCCCcc',
  'CCCCCCCCCCCCCCCCCCCCcc',
  'CCCCCCCCCCCCCCCCCCCCcc',
  'CCCC1111111111111CCCcc',
  'CCCC1111111111111CCCcc',
  'CCCCCCCCCCCCCCCCCCCCcc',
  'CCCCCCCCCCCCCCCCCCCCcc',
  'CCCCCCCCCCCCCCCCCCCCcc',
  'CCoPPPPPPPPPPPPPPPPPpc',
  'CCPpPpPpPpPpPpPpPpPppc',
  'CCPPPPPPPPPPPPPPPPPPpc',
  'cjppppppppppppppppppyj',
  '......................',
  '......................',
];
export const BLK_SHOE: Grid = [
  '......................',
  '......................',
  '......................',
  '...gGGGGGGGGc.........',
  '..gGGGGGGGGGCc........',
  '..GGOOOOOOGGCc........',
  '..GGGGGGGGGGCCc.......',
  '..GGOOOOOOGGCCc.......',
  '..GGGGGGGGGGCCCc......',
  '.oPPPPPPPPPPPPPPPpp...',
  '.oPPPPPPPPPPPPPPPPPpp.',
  'oPPPPPPPPPPPPPPPPPPPpp',
  'oPPPPPPPPPPPPPPPPPPPpp',
  'oPPPPPPPPPPPPPPPPPPPpp',
  'oPPPPPPPPPPPPPPPPPPPpp',
  'MMMMMMMMMMMMMMMMMMMMMm',
  'MMMMMMMMMMMMMMMMMMMMMm',
  'mmmmmmmmmmmmmmmmmmmmmz',
  '......................',
  '......................',
  '......................',
  '......................',
];
export const BLK_SOAP: Grid = [
  '................gOOg..',
  '...........gOg.gOOOOg.',
  '..........gOOOggOOOOg.',
  '...........gOg..gOOg..',
  '......................',
  '.gggggggggggggggggggc.',
  'gGGGGGGGGGGGGGGGGGGGGc',
  'gGGGOOOGGGGGGGGGGGGGcc',
  'CCCCCCCCCCCCCCCCCCCCcc',
  'CCCCCCCCCCCCCCCCCCCCcc',
  'CCCCCCCCCCCCCCCCCCCCcc',
  'CCCCCCCCCCCCCCCCCCCCcc',
  'CCCCCCCCCCCCCCCCCCCCcc',
  'CCCCCCCCCCCCCCCCCCCCcc',
  'CCCCCCCCCCCCCCCCCCCCcc',
  'CCCCCCCCCCCCCCCCCCCCcc',
  'cccccccccccccccccccccc',
  '.jjjjjjjjjjjjjjjjjjjj.',
  '......................',
  '......................',
  '......................',
  '......................',
];
export const BLK_SPOOL: Grid = [
  '......................',
  'uuuuuuuuuuuuuuuuuuuuuw',
  'uWWWWWWWWWWWWWWWWWWWww',
  'WWWWWWWWWWWWWWWWWWWWww',
  'wwwwwwwwwwwwwwwwwwwwvv',
  '..GGgCCCCCCCCCCCCCCc..',
  '..GgCCCCCCCCCCCCCCcc..',
  '..GGgcccccccccccccjc..',
  '..GgCCCCCCCCCCCCCCcc..',
  '..GGgcccccccccccccjc..',
  '..GgCCCCCCCCCCCCCCcc..',
  '..GGgcccccccccccccjc..',
  '..GgCCCCCCCCCCCCCCcc..',
  '..GGgcccccccccccccjc..',
  '..GgCCCCCCCCCCCCCCcc..',
  '..GGgcccccccccccccjc..',
  '..GgCCCCCCCCCCCCCCcc..',
  'uuuuuuuuuuuuuuuuuuuuuw',
  'uWWWWWWWWWWWWWWWWWWWww',
  'wwwwwwwwwwwwwwwwwwwwvv',
  '.vvvvvvvvvvvvvvvvvvvv.',
  '......................',
];
export const BLK_POT: Grid = [
  '.....lB...lB....lB....',
  '...lBBBb.lBBb..lBBb...',
  '..lBBBBblBBBBblBBBBb..',
  '..BBBBbbBBBBbbBBBBbb..',
  '...bbbb..bbbb..bbbb...',
  'gGGGGGGGGGGGGGGGGGGGGc',
  'GGGGGGGGGGGGGGGGGGGGcc',
  'GGGGGGGGGGGGGGGGGGGGcc',
  'ccccccccccccccccccccjj',
  '.gGCCCCCCCCCCCCCCCCcj.',
  '.gGCCCCCCCCCCCCCCCCcj.',
  '.gGCCCCCCCCCCCCCCCCcj.',
  '..gGCCCCCCCCCCCCCCcj..',
  '..gGCCCCCCCCCCCCCCcj..',
  '..gGCCCCCCCCCCCCCCcj..',
  '..gGCCCCCCCCCCCCCCcj..',
  '...gCCCCCCCCCCCCCcj...',
  '...gCCCCCCCCCCCCCcj...',
  '...cccccccccccccccj...',
  '....jjjjjjjjjjjjjj....',
  '......................',
  '......................',
];
export const BLK_BOX: Grid = [
  '......................',
  'qqqqqqqqqeTTtqqqqqqqqq',
  'qQqqqqqqqeTTtqqqqqqqqk',
  'qqqqqqqqqeTTtqqqqqqqqk',
  'qkkkkkkkkeTTtkkkkkkkkk',
  'kkkkkkkkkeTTtkkkkkkkkx',
  'qKKKKKKKKeTTtKKKKKKKKk',
  'qKKKKKKKKeTTtKKKKKKKKk',
  'qKKKKKKKKeTTtKKKKKKKKk',
  'qKKKKKKKKeTTtKKKKKKKKk',
  'qKKKKKKKKeTTtKKKKKKKKk',
  'qKKKKKKKKeTTtKKKKKKKKk',
  'qKKKKKKKKeTTtKKKKKKKKk',
  'qKKKKKKKKeTTtKKKKKKKKk',
  'qKKKKKKKKeTTtKKKKKKKKk',
  'qKKKKKKKKeTTtKKKKKKKKk',
  'qKKKKKKKKeTTtKKKKKKKKk',
  'qKKKKKKKKeTTtKKKKKKKKk',
  'qKKKKKKKKeTTtKKKKKKKKk',
  'kkkkkkkkkkkkkkkkkkkkkk',
  'xxxxxxxxxxxxxxxxxxxxxx',
  '......................',
];
/** 나무 글자 블록 (기본): 윗면 · 앞면 · 옆면 · 빨간 ㅁ 무늬 */
export const BLK_BLOCK: Grid = [
  '......................',
  'gggggggggggggggggggggc',
  'gGGGGGGGGGGGGGGGGGGGcc',
  'gGGGGGGGGGGGGGGGGGGGcc',
  'gGGGGGGGGGGGGGGGGGGGcc',
  'GGGGGGGGGGGGGGGGGGcccc',
  'CCCCCCCCCCCCCCCCCCcccc',
  'CCCCCCCCCCCCCCCCCCcccc',
  'CCCCRRRRRRRRRCCCCCcccc',
  'CCCCRRRRRRRRRCCCCCcccc',
  'CCCCRRCCCCCRRCCCCCcccc',
  'CCCCRRCCCCCRRCCCCCcccc',
  'CCCCRRCCCCCRRCCCCCcccc',
  'CCCCRRCCCCCRRCCCCCcccc',
  'CCCCRRCCCCCRRCCCCCcccc',
  'CCCCRRRRRRRRRCCCCCcccc',
  'CCCCRRRRRRRRRCCCCCcccc',
  'CCCCCCCCCCCCCCCCCCcccc',
  'CCCCCCCCCCCCCCCCCCcccc',
  'cccccccccccccccccccccc',
  'jjjjjjjjjjjjjjjjjjjjjj',
  '......................',
];
